package cities_codes;

import java.util.HashMap;

@SuppressWarnings("serial")
public class CitiesCodes_Z extends HashMap<String, String> {

    public CitiesCodes_Z(){
        this.put("Z100", "ALBANIA");
        this.put("Z101", "ANDORRA");
        this.put("Z102", "AUSTRIA");
        this.put("Z103", "BELGIO");
        this.put("Z104", "BULGARIA");
        this.put("Z106", "CITTA' DEL VATICANO");
        this.put("Z107", "DANIMARCA");
        this.put("Z108", "FAER OER (ISOLE)");
        this.put("Z109", "FINLANDIA");
        this.put("Z110", "FRANCIA");
        this.put("Z112", "GERMANIA");
        this.put("Z113", "GIBILTERRA");
        this.put("Z114", "GRAN BRETAGNA E IRLANDA DEL NORD");
        this.put("Z115", "GRECIA");
        this.put("Z116", "IRLANDA=EIRE");
        this.put("Z117", "ISLANDA");
        this.put("Z118", "SERBIA E MONTENEGRO");
        this.put("Z119", "LIECHTENSTEIN");
        this.put("Z120", "LUSSEMBURGO");
        this.put("Z121", "MALTA");
        this.put("Z122", "MAN (ISOLA)");
        this.put("Z123", "MONACO");
        this.put("Z124", "NORMANNE (ISOLE)=ISOLE DEL CANALE");
        this.put("Z125", "NORVEGIA");
        this.put("Z126", "PAESI BASSI");
        this.put("Z127", "REPUBBLICA DI POLONIA");
        this.put("Z128", "PORTOGALLO");
        this.put("Z129", "ROMANIA");
        this.put("Z130", "SAN MARINO");
        this.put("Z131", "SPAGNA");
        this.put("Z132", "SVEZIA");
        this.put("Z133", "SVIZZERA");
        this.put("Z134", "UNGHERIA");
        this.put("Z135", "UNIONE REPUBBLICHE SOCIALISTE SOVIETICHE");
        this.put("Z138", "UCRAINA");
        this.put("Z139", "BIELORUSSIA=RUSSIA BIANCA");
        this.put("Z140", "MOLDAVIA");
        this.put("Z144", "ESTONIA");
        this.put("Z145", "LETTONIA");
        this.put("Z146", "LITUANIA");
        this.put("Z148", "MACEDONIA");
        this.put("Z149", "CROAZIA");
        this.put("Z150", "SLOVENIA");
        this.put("Z153", "BOSNIA ED ERZEGOVINA");
        this.put("Z154", "RUSSIA=FEDERAZIONE RUSSA");
        this.put("Z155", "SLOVACCHIA");
        this.put("Z156", "CECA REPUBBLICA");
        this.put("Z157", "MONTENEGRO");
        this.put("Z158", "SERBIA");
        this.put("Z160", "KOSOVO");
        this.put("Z200", "AFGHANISTAN");
        this.put("Z203", "ARABIA SAUDITA");
        this.put("Z204", "BAHREIN");
        this.put("Z205", "BHUTAN");
        this.put("Z206", "BIRMANIA");
        this.put("Z207", "BRUNEI");
        this.put("Z208", "CAMBOGIA");
        this.put("Z209", "SRI LANKA");
        this.put("Z210", "CINA REPUBBLICA POPOLARE");
        this.put("Z211", "CIPRO");
        this.put("Z212", "COCOS (ISOLE)");
        this.put("Z213", "COREA DEL SUD");
        this.put("Z214", "COREA DEL NORD");
        this.put("Z215", "EMIRATI ARABI UNITI");
        this.put("Z216", "FILIPPINE");
        this.put("Z217", "REPUBBLICA DELLA CINA NAZIONALE=TAIWAN");
        this.put("Z218", "GAZA (TERRITORIO DI)");
        this.put("Z219", "GIAPPONE");
        this.put("Z220", "GIORDANIA");
        this.put("Z222", "INDIA");
        this.put("Z223", "INDONESIA");
        this.put("Z224", "IRAN");
        this.put("Z225", "IRAQ");
        this.put("Z226", "ISRAELE");
        this.put("Z227", "KUWAIT");
        this.put("Z228", "LAOS");
        this.put("Z229", "LIBANO");
        this.put("Z230", "MALAYSIA");
        this.put("Z231", "MACAO");
        this.put("Z232", "MALDIVE");
        this.put("Z233", "MONGOLIA");
        this.put("Z234", "NEPAL");
        this.put("Z235", "OMAN");
        this.put("Z236", "PAKISTAN");
        this.put("Z237", "QATAR");
        this.put("Z240", "SIRIA");
        this.put("Z241", "THAILANDIA");
        this.put("Z243", "TURCHIA");
        this.put("Z246", "YEMEN");
        this.put("Z248", "SINGAPORE");
        this.put("Z249", "BANGLADESH");
        this.put("Z251", "VIETNAM");
        this.put("Z252", "ARMENIA");
        this.put("Z253", "AZERBAIGIAN");
        this.put("Z254", "GEORGIA");
        this.put("Z255", "KAZAKISTAN");
        this.put("Z256", "KIRGHIZISTAN");
        this.put("Z257", "TAGIKISTAN");
        this.put("Z258", "TURKEMENISTAN");
        this.put("Z259", "UZBEKISTAN");
        this.put("Z300", "NAMIBIA");
        this.put("Z301", "ALGERIA");
        this.put("Z302", "ANGOLA");
        this.put("Z305", "BURUNDI");
        this.put("Z306", "CAMERUN");
        this.put("Z307", "CAPO VERDE");
        this.put("Z308", "CENTRAFRICANA REPUBBLICA");
        this.put("Z309", "CIAD");
        this.put("Z310", "COMORE (ISOLE)");
        this.put("Z311", "CONGO REPUBBLICA POPOLARE");
        this.put("Z312", "CONGO REPUBBLICA DEMOCRATICA");
        this.put("Z313", "COSTA D'AVORIO");
        this.put("Z314", "BENIN");
        this.put("Z315", "ETIOPIA");
        this.put("Z316", "GABON");
        this.put("Z317", "GAMBIA");
        this.put("Z318", "GHANA");
        this.put("Z319", "GUINEA");
        this.put("Z320", "GUINEA BISSAU");
        this.put("Z321", "GUINEA EQUATORIALE");
        this.put("Z322", "KENYA");
        this.put("Z324", "LA REUNION (ISOLA)");
        this.put("Z325", "LIBERIA");
        this.put("Z326", "LIBIA");
        this.put("Z327", "MADAGASCAR");
        this.put("Z328", "MALAWI");
        this.put("Z329", "MALI");
        this.put("Z330", "MAROCCO");
        this.put("Z331", "MAURITANIA");
        this.put("Z332", "MAURIZIO");
        this.put("Z333", "MOZAMBICO");
        this.put("Z334", "NIGER");
        this.put("Z335", "NIGERIA");
        this.put("Z336", "EGITTO");
        this.put("Z337", "ZIMBABWE");
        this.put("Z338", "RUANDA");
        this.put("Z339", "SAHARA SPAGNOLO");
        this.put("Z340", "SANT'ELENA (ISOLA)");
        this.put("Z341", "SAO TOME' E PRINCIPE");
        this.put("Z342", "SEICELLE (ISOLE)");
        this.put("Z343", "SENEGAL");
        this.put("Z344", "SIERRA LEONE");
        this.put("Z345", "SOMALIA");
        this.put("Z347", "SUDAFRICANA REPUBBLICA");
        this.put("Z348", "SUDAN");
        this.put("Z349", "SWAZILAND");
        this.put("Z351", "TOGO");
        this.put("Z352", "TUNISIA");
        this.put("Z353", "UGANDA");
        this.put("Z354", "BURKINA");
        this.put("Z355", "ZAMBIA");
        this.put("Z357", "TANZANIA");
        this.put("Z358", "BOTSWANA");
        this.put("Z359", "LESOTHO");
        this.put("Z360", "MAYOTTE (ISOLA)");
        this.put("Z361", "GIBUTI");
        this.put("Z368", "ERITREA");
        this.put("Z400", "BERMUDA (ISOLE)");
        this.put("Z401", "CANADA");
        this.put("Z402", "GROENLANDIA");
        this.put("Z403", "SAINT PIERRE ET MIQUELON (ISOLE)");
        this.put("Z404", "STATI UNITI D'AMERICA");
        this.put("Z501", "ANTILLE OLANDESI");
        this.put("Z502", "BAHAMA");
        this.put("Z503", "COSTA RICA");
        this.put("Z504", "CUBA");
        this.put("Z505", "DOMINICANA REPUBBLICA");
        this.put("Z506", "EL SALVADOR");
        this.put("Z507", "GIAMAICA");
        this.put("Z508", "GUADALUPA");
        this.put("Z509", "GUATEMALA");
        this.put("Z510", "HAITI");
        this.put("Z511", "HONDURAS");
        this.put("Z512", "BELIZE");
        this.put("Z513", "MARTINICA");
        this.put("Z514", "MESSICO");
        this.put("Z515", "NICARAGUA");
        this.put("Z516", "PANAMA'");
        this.put("Z517", "PANAMA ZONA DEL CANALE");
        this.put("Z518", "PUERTO RICO");
        this.put("Z519", "TURKS E CAICOS (ISOLE)");
        this.put("Z520", "VERGINI AMERICANE (ISOLE)");
        this.put("Z522", "BARBADOS");
        this.put("Z523", "ANTILLE BRITANNICHE");
        this.put("Z524", "GRENADA");
        this.put("Z525", "VERGINI BRITANNICHE (ISOLE)");
        this.put("Z526", "DOMINICA");
        this.put("Z527", "SAINT LUCIA");
        this.put("Z528", "SAINT VINCENT E GRENADINE");
        this.put("Z529", "ANGUILLA (ISOLA)");
        this.put("Z530", "CAYMAN (ISOLE)");
        this.put("Z531", "MONTSERRAT");
        this.put("Z532", "ANTIGUA E BARBUDA");
        this.put("Z533", "SAINT KITTS E NEVIS=SAINT CHRISTOPHER E NEVIS");
        this.put("Z600", "ARGENTINA");
        this.put("Z601", "BOLIVIA");
        this.put("Z602", "BRASILE");
        this.put("Z603", "CILE");
        this.put("Z604", "COLOMBIA");
        this.put("Z605", "ECUADOR");
        this.put("Z606", "GUYANA");
        this.put("Z607", "GUAYANA=GUIANA FRANCESE");
        this.put("Z608", "SURINAME");
        this.put("Z609", "MALVINE=FALKLAND (ISOLE)");
        this.put("Z610", "PARAGUAY");
        this.put("Z611", "PERU'");
        this.put("Z612", "TRINIDAD E TOBAGO");
        this.put("Z613", "URUGUAY");
        this.put("Z614", "VENEZUELA");
        this.put("Z700", "AUSTRALIA");
        this.put("Z701", "CAROLINE (ISOLE)");
        this.put("Z702", "CHRISTMAS (ISOLA)");
        this.put("Z703", "COOK (ISOLE)");
        this.put("Z704", "FIGI=VITI");
        this.put("Z705", "GILBERT E ELLICE (ISOLE)");
        this.put("Z706", "GUAM (ISOLA)");
        this.put("Z707", "IRIAN OCCIDENTALE");
        this.put("Z708", "MACQUARIE (ISOLE)");
        this.put("Z710", "MARIANNE (ISOLE)");
        this.put("Z711", "MARSHALL");
        this.put("Z712", "MIDWAY (ISOLE)");
        this.put("Z713", "NAURU");
        this.put("Z714", "NIUE=SAVAGE (ISOLE)");
        this.put("Z715", "NORFOLK (ISOLE E ISOLE DEL MAR DEI CORALLI)");
        this.put("Z716", "NUOVA CALEDONIA (ISOLE E DIPENDENZE)");
        this.put("Z719", "NUOVA ZELANDA");
        this.put("Z721", "ISOLE CILENE (PASQUA E SALA Y GOMEZ)");
        this.put("Z722", "PITCAIRN (E DIPENDENZE)");
        this.put("Z723", "POLINESIA FRANCESE (ISOLE)");
        this.put("Z724", "SALOMONE");
        this.put("Z725", "SAMOA AMERICANE (ISOLE)");
        this.put("Z726", "SAMOA");
        this.put("Z727", "TOKELAU=ISOLE DELL'UNIONE");
        this.put("Z728", "TONGA=ISOLE DEGLI AMICI");
        this.put("Z729", "WALLIS E FUTUNA (ISOLE)");
        this.put("Z730", "PAPUA NUOVA GUINEA");
        this.put("Z731", "KIRIBATI");
        this.put("Z732", "TUVALU");
        this.put("Z733", "VANUATU");
        this.put("Z734", "PALAU");
        this.put("Z735", "MICRONESIA STATI FEDERATI");
        this.put("Z800", "DIPENDENZE CANADESI");
        this.put("Z801", "DIPENDENZE NORVEGESI ARTICHE");
        this.put("Z802", "DIPENDENZE RUSSE");
        this.put("Z900", "DIPENDENZE AUSTRALIANE");
        this.put("Z901", "DIPENDENZE BRITANNICHE");
        this.put("Z902", "DIPENDENZE FRANCESI");
        this.put("Z903", "DIPENDENZE NEOZELANDESI");
        this.put("Z904", "DIPENDENZE NORVEGESI ANTARTICHE");
        this.put("Z905", "DIPENDENZE STATUNITENSI");
        this.put("Z906", "DIPENDENZE SUDAFRICANE");       
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
