package cities_codes;

import java.util.HashMap;

@SuppressWarnings("serial")
public class CitiesCodes_E extends HashMap<String, String> {

    public CitiesCodes_E(){
    	this.put("E001", "GHEMME");
    	this.put("E003", "GHIFFA");
    	this.put("E004", "GHILARZA");
    	this.put("E006", "GHISALBA");
    	this.put("E007", "GHISLARENGO");
    	this.put("E008", "GIACCIANO CON BARUCHELLA");
    	this.put("E009", "GIAGLIONE");
    	this.put("E010", "GIANICO");
    	this.put("E011", "GIANO VETUSTO");
    	this.put("E012", "GIANO DELL'UMBRIA");
    	this.put("E013", "GIARDINELLO");
    	this.put("E014", "GIARDINI-NAXOS");
    	this.put("E015", "GIAROLE");
    	this.put("E016", "GIARRATANA");
    	this.put("E017", "GIARRE");
    	this.put("E019", "GIAVE");
    	this.put("E020", "GIAVENO");
    	this.put("E021", "GIAVERA DEL MONTELLO");
    	this.put("E022", "GIBA");
    	this.put("E023", "GIBELLINA");
    	this.put("E024", "GIFFLENGA");
    	this.put("E025", "GIFFONE");
    	this.put("E026", "GIFFONI SEI CASALI");
    	this.put("E027", "GIFFONI VALLE PIANA");
    	this.put("E028", "GIGNESE");
    	this.put("E029", "GIGNOD");
    	this.put("E030", "GILDONE");
    	this.put("E031", "GIMIGLIANO");
    	this.put("E033", "GINESTRA");
    	this.put("E034", "GINESTRA DEGLI SCHIAVONI");
    	this.put("E036", "GINOSA");
    	this.put("E037", "GIOI");
    	this.put("E038", "GIOIA DEL COLLE");
    	this.put("E039", "GIOIA SANNITICA");
    	this.put("E040", "GIOIA DEI MARSI");
    	this.put("E041", "GIOIA TAURO");
    	this.put("E043", "GIOIOSA MAREA");
    	this.put("E044", "GIOIOSA IONICA");
    	this.put("E045", "GIOVE");
    	this.put("E047", "GIOVINAZZO");
    	this.put("E048", "GIOVO");
    	this.put("E049", "GIRASOLE");
    	this.put("E050", "GIRIFALCO");
    	this.put("E051", "GIRONICO");
    	this.put("E052", "GISSI");
    	this.put("E053", "GIUGGIANELLO");
    	this.put("E054", "GIUGLIANO IN CAMPANIA");
    	this.put("E055", "GIULIANA");
    	this.put("E056", "GIULIANO TEATINO");
    	this.put("E057", "GIULIANO DI ROMA");
    	this.put("E058", "GIULIANOVA");
    	this.put("E059", "GIUNCUGNANO");
    	this.put("E060", "GIUNGANO");
    	this.put("E061", "GIURDIGNANO");
    	this.put("E062", "GIUSSAGO");
    	this.put("E063", "GIUSSANO");
    	this.put("E064", "GIUSTENICE");
    	this.put("E065", "GIUSTINO");
    	this.put("E066", "GIUSVALLA");
    	this.put("E067", "GIVOLETTO");
    	this.put("E068", "GIZZERIA");
    	this.put("E069", "GLORENZA .GLURNS.");
    	this.put("E070", "SESTA GODANO");
    	this.put("E071", "GODEGA DI SANT'URBANO");
    	this.put("E072", "GODIASCO SALICE TERME");
    	this.put("E074", "GODRANO");
    	this.put("E078", "GOITO");
    	this.put("E079", "GOLASECCA");
    	this.put("E081", "GOLFERENZO");
    	this.put("E082", "GOMBITO");
    	this.put("E083", "GONARS");
    	this.put("E084", "GONI");
    	this.put("E085", "GONNOSFANADIGA");
    	this.put("E086", "GONNESA");
    	this.put("E087", "GONNOSCODINA");
    	this.put("E088", "GONNOSTRAMATZA");
    	this.put("E089", "GONZAGA");
    	this.put("E090", "GORDONA");
    	this.put("E091", "GORGA");
    	this.put("E092", "GORGO AL MONTICANO");
    	this.put("E093", "GORGOGLIONE");
    	this.put("E094", "GORGONZOLA");
    	this.put("E096", "GORIANO SICOLI");
    	this.put("E098", "GORIZIA");
    	this.put("E100", "GORLAGO");
    	this.put("E101", "GORLA MAGGIORE");
    	this.put("E102", "GORLA MINORE");
    	this.put("E103", "GORLE");
    	this.put("E104", "GORNATE-OLONA");
    	this.put("E106", "GORNO");
    	this.put("E107", "GORO");
    	this.put("E109", "GORRETO");
    	this.put("E111", "GORZEGNO");
    	this.put("E113", "GOSALDO");
    	this.put("E114", "GOSSOLENGO");
    	this.put("E115", "GOTTASECCA");
    	this.put("E116", "GOTTOLENGO");
    	this.put("E118", "GOVONE");
    	this.put("E120", "GOZZANO");
    	this.put("E122", "GRADARA");
    	this.put("E124", "GRADISCA D'ISONZO");
    	this.put("E125", "GRADO");
    	this.put("E126", "GRADOLI");
    	this.put("E127", "GRAFFIGNANA");
    	this.put("E128", "GRAFFIGNANO");
    	this.put("E130", "GRAGLIA");
    	this.put("E131", "GRAGNANO");
    	this.put("E132", "GRAGNANO TREBBIENSE");
    	this.put("E133", "GRAMMICHELE");
    	this.put("E134", "GRANA");
    	this.put("E135", "GRANAGLIONE");
    	this.put("E136", "GRANAROLO DELL'EMILIA");
    	this.put("E138", "GRANCONA");
    	this.put("E139", "GRANDATE");
    	this.put("E141", "GRANDOLA ED UNITI");
    	this.put("E142", "GRANITI");
    	this.put("E143", "GRANOZZO CON MONTICELLO");
    	this.put("E144", "GRANTOLA");
    	this.put("E145", "GRANTORTO");
    	this.put("E146", "GRANZE");
    	this.put("E147", "GRASSANO");
    	this.put("E148", "GRASSOBBIO");
    	this.put("E149", "GRATTERI");
    	this.put("E150", "GRAUNO");
    	this.put("E151", "GRAVEDONA");
    	this.put("E152", "GRAVELLONA LOMELLINA");
    	this.put("E153", "GRAVELLONA TOCE");
    	this.put("E154", "GRAVERE");
    	this.put("E155", "GRAVINA IN PUGLIA");
    	this.put("E156", "GRAVINA DI CATANIA");
    	this.put("E158", "GRAZZANISE");
    	this.put("E159", "GRAZZANO BADOGLIO");
    	this.put("E160", "GRECCIO");
    	this.put("E161", "GRECI");
    	this.put("E163", "GREGGIO");
    	this.put("E164", "GREMIASCO");
    	this.put("E165", "GRESSAN");
    	this.put("E167", "GRESSONEY-LA-TRINITE'");
    	this.put("E168", "GRESSONEY-SAINT-JEAN");
    	this.put("E169", "GREVE IN CHIANTI");
    	this.put("E170", "GREZZAGO");
    	this.put("E171", "GREZZANA");
    	this.put("E172", "GRIANTE");
    	this.put("E173", "GRICIGNANO DI AVERSA");
    	this.put("E177", "GRIGNASCO");
    	this.put("E178", "GRIGNO");
    	this.put("E179", "GRIMACCO");
    	this.put("E180", "GRIMALDI");
    	this.put("E182", "GRINZANE CAVOUR");
    	this.put("E184", "GRISIGNANO DI ZOCCO");
    	this.put("E185", "GRISOLIA");
    	this.put("E187", "GRIZZANA MORANDI");
    	this.put("E188", "GROGNARDO");
    	this.put("E189", "GROMO");
    	this.put("E191", "GRONDONA");
    	this.put("E192", "GRONE");
    	this.put("E193", "GRONTARDO");
    	this.put("E195", "GROPELLO CAIROLI");
    	this.put("E196", "GROPPARELLO");
    	this.put("E199", "GROSCAVALLO");
    	this.put("E200", "GROSIO");
    	this.put("E201", "GROSOTTO");
    	this.put("E202", "GROSSETO");
    	this.put("E203", "GROSSO");
    	this.put("E204", "GROTTAFERRATA");
    	this.put("E205", "GROTTAGLIE");
    	this.put("E206", "GROTTAMINARDA");
    	this.put("E207", "GROTTAMMARE");
    	this.put("E208", "GROTTAZZOLINA");
    	this.put("E209", "GROTTE");
    	this.put("E210", "GROTTE DI CASTRO");
    	this.put("E212", "GROTTERIA");
    	this.put("E213", "GROTTOLE");
    	this.put("E214", "GROTTOLELLA");
    	this.put("E215", "GRUARO");
    	this.put("E216", "GRUGLIASCO");
    	this.put("E217", "GRUMELLO CREMONESE ED UNITI");
    	this.put("E219", "GRUMELLO DEL MONTE");
    	this.put("E221", "GRUMENTO NOVA");
    	this.put("E222", "GRUMES");
    	this.put("E223", "GRUMO APPULA");
    	this.put("E224", "GRUMO NEVANO");
    	this.put("E226", "GRUMOLO DELLE ABBADESSE");
    	this.put("E227", "GUAGNANO");
    	this.put("E228", "GUALDO");
    	this.put("E229", "GUALDO CATTANEO");
    	this.put("E230", "GUALDO TADINO");
    	this.put("E232", "GUALTIERI");
    	this.put("E233", "GUALTIERI SICAMINO'");
    	this.put("E234", "GUAMAGGIORE");
    	this.put("E235", "GUANZATE");
    	this.put("E236", "GUARCINO");
    	this.put("E237", "GUARDABOSONE");
    	this.put("E238", "GUARDAMIGLIO");
    	this.put("E239", "GUARDAVALLE");
    	this.put("E240", "GUARDA VENETA");
    	this.put("E241", "GUARDEA");
    	this.put("E242", "GUARDIA PIEMONTESE");
    	this.put("E243", "GUARDIAGRELE");
    	this.put("E244", "GUARDIALFIERA");
    	this.put("E245", "GUARDIA LOMBARDI");
    	this.put("E246", "GUARDIA PERTICARA");
    	this.put("E248", "GUARDIAREGIA");
    	this.put("E249", "GUARDIA SANFRAMONDI");
    	this.put("E250", "GUARDISTALLO");
    	this.put("E251", "GUARENE");
    	this.put("E252", "GUASILA");
    	this.put("E253", "GUASTALLA");
    	this.put("E255", "GUAZZORA");
    	this.put("E256", "GUBBIO");
    	this.put("E258", "GUDO VISCONTI");
    	this.put("E259", "GUGLIONESI");
    	this.put("E261", "GUIDIZZOLO");
    	this.put("E263", "GUIDONIA MONTECELIO");
    	this.put("E264", "GUIGLIA");
    	this.put("E265", "SIZIANO");
    	this.put("E266", "GUILMI");
    	this.put("E269", "GURRO");
    	this.put("E270", "GUSPINI");
    	this.put("E271", "GUSSAGO");
    	this.put("E272", "GUSSOLA");
    	this.put("E273", "HONE");
    	this.put("E274", "JACURSO");
    	this.put("E280", "IDRO");
    	this.put("E281", "IGLESIAS");
    	this.put("E282", "IGLIANO");
    	this.put("E283", "ILBONO");
    	this.put("E284", "ILLASI");
    	this.put("E285", "ILLORAI");
    	this.put("E287", "IMBERSAGO");
    	this.put("E288", "IMER");
    	this.put("E289", "IMOLA");
    	this.put("E290", "IMPERIA");
    	this.put("E291", "IMPRUNETA");
    	this.put("E292", "INARZO");
    	this.put("E295", "INCISA SCAPACCINO");
    	this.put("E296", "INCISA IN VAL D'ARNO");
    	this.put("E297", "INCUDINE");
    	this.put("E299", "INDUNO OLONA");
    	this.put("E301", "INGRIA");
    	this.put("E304", "INTRAGNA");
    	this.put("E305", "INTROBIO");
    	this.put("E306", "INTROD");
    	this.put("E307", "INTRODACQUA");
    	this.put("E308", "INTROZZO");
    	this.put("E309", "INVERIGO");
    	this.put("E310", "INVERNO E MONTELEONE");
    	this.put("E311", "INVERSO PINASCA");
    	this.put("E313", "INVERUNO");
    	this.put("E314", "INVORIO");
    	this.put("E317", "INZAGO");
    	this.put("E320", "JOLANDA DI SAVOIA");
    	this.put("E321", "IONADI");
    	this.put("E323", "IRGOLI");
    	this.put("E325", "IRMA");
    	this.put("E326", "IRSINA");
    	this.put("E327", "ISASCA");
    	this.put("E328", "ISCA SULLO IONIO");
    	this.put("E329", "ISCHIA");
    	this.put("E330", "ISCHIA DI CASTRO");
    	this.put("E332", "ISCHITELLA");
    	this.put("E333", "ISEO");
    	this.put("E334", "ISERA");
    	this.put("E335", "ISERNIA");
    	this.put("E336", "ISILI");
    	this.put("E337", "ISNELLO");
    	this.put("E338", "ISOLA D'ASTI");
    	this.put("E339", "ISOLA DI CAPO RIZZUTO");
    	this.put("E340", "ISOLA DEL LIRI");
    	this.put("E341", "ISOLA DEL CANTONE");
    	this.put("E342", "MADESIMO");
    	this.put("E343", "ISOLA DEL GRAN SASSO D'ITALIA");
    	this.put("E345", "ISOLABELLA");
    	this.put("E346", "ISOLABONA");
    	this.put("E348", "ISOLA DEL GIGLIO");
    	this.put("E349", "ISOLA DELLA SCALA");
    	this.put("E350", "ISOLA DELLE FEMMINE");
    	this.put("E351", "ISOLA DEL PIANO");
    	this.put("E353", "ISOLA DI FONDRA");
    	this.put("E354", "ISOLA VICENTINA");
    	this.put("E356", "ISOLA DOVARESE");
    	this.put("E358", "ISOLA RIZZA");
    	this.put("E360", "ISOLA SANT'ANTONIO");
    	this.put("E363", "ISOLE TREMITI");
    	this.put("E364", "ISORELLA");
    	this.put("E365", "ISPANI");
    	this.put("E366", "ISPICA");
    	this.put("E367", "ISPRA");
    	this.put("E368", "ISSIGLIO");
    	this.put("E369", "ISSIME");
    	this.put("E370", "ISSO");
    	this.put("E371", "ISSOGNE");
    	this.put("E372", "VASTO");
    	this.put("E373", "ISTRANA");
    	this.put("E374", "ITALA");
    	this.put("E375", "ITRI");
    	this.put("E376", "ITTIREDDU");
    	this.put("E377", "ITTIRI");
    	this.put("E378", "IVANO FRACENA");
    	this.put("E379", "IVREA");
    	this.put("E380", "IZANO");
    	this.put("E381", "JELSI");
    	this.put("E382", "JENNE");
    	this.put("E386", "JERAGO CON ORAGO");
    	this.put("E387", "JERZU");
    	this.put("E388", "JESI");
    	this.put("E389", "JOPPOLO");
    	this.put("E390", "JOPPOLO GIANCAXIO");
    	this.put("E391", "JOVENCAN");
    	this.put("E392", "LABICO");
    	this.put("E393", "LABRO");
    	this.put("E394", "LA CASSA");
    	this.put("E395", "LACCHIARELLA");
    	this.put("E396", "LACCO AMENO");
    	this.put("E397", "LACEDONIA");
    	this.put("E398", "LACES .LATSCH.");
    	this.put("E400", "LACONI");
    	this.put("E401", "LAERRU");
    	this.put("E402", "LAGANADI");
    	this.put("E403", "LAGHI");
    	this.put("E405", "LAGLIO");
    	this.put("E406", "LAGNASCO");
    	this.put("E407", "LAGO");
    	this.put("E409", "LAGONEGRO");
    	this.put("E410", "LAGOSANTO");
    	this.put("E412", "LAGUNDO .ALGUND.");
    	this.put("E413", "LAJATICO");
    	this.put("E414", "LAIGUEGLIA");
    	this.put("E415", "LAINATE");
    	this.put("E416", "LAINO");
    	this.put("E417", "LAINO BORGO");
    	this.put("E419", "LAINO CASTELLO");
    	this.put("E420", "LAION .LAJEN.");
    	this.put("E421", "LAIVES .LEIFERS.");
    	this.put("E422", "LALLIO");
    	this.put("E423", "LA LOGGIA");
    	this.put("E424", "LAMA DEI PELIGNI");
    	this.put("E425", "LA MADDALENA");
    	this.put("E426", "LAMA MOCOGNO");
    	this.put("E428", "LAMBRUGO");
    	this.put("E429", "LAMON");
    	this.put("E430", "LA MORRA");
    	this.put("E431", "LAMPEDUSA E LINOSA");
    	this.put("E432", "LAMPORECCHIO");
    	this.put("E433", "LAMPORO");
    	this.put("E434", "LANA .LANA.");
    	this.put("E435", "LANCIANO");
    	this.put("E436", "LANDIONA");
    	this.put("E437", "LANDRIANO");
    	this.put("E438", "LANGHIRANO");
    	this.put("E439", "LANGOSCO");
    	this.put("E441", "LANUSEI");
    	this.put("E443", "LANZADA");
    	this.put("E444", "LANZO D'INTELVI");
    	this.put("E445", "LANZO TORINESE");
    	this.put("E447", "LAPEDONA");
    	this.put("E448", "LAPIO");
    	this.put("E450", "LAPPANO");
    	this.put("E451", "LARCIANO");
    	this.put("E452", "LARDARO");
    	this.put("E454", "LARDIRAGO");
    	this.put("E455", "LARI");
    	this.put("E456", "LARINO");
    	this.put("E457", "LASA .LAAS.");
    	this.put("E458", "LA SALLE");
    	this.put("E459", "LASCARI");
    	this.put("E461", "LASINO");
    	this.put("E462", "LASNIGO");
    	this.put("E463", "LA SPEZIA");
    	this.put("E464", "LAS PLASSAS");
    	this.put("E465", "LASTEBASSE");
    	this.put("E466", "LASTRA A SIGNA");
    	this.put("E467", "LATERA");
    	this.put("E468", "LATERINA");
    	this.put("E469", "LATERZA");
    	this.put("E470", "LA THUILE");
    	this.put("E471", "LATIANO");
    	this.put("E472", "LATINA");
    	this.put("E473", "LATISANA");
    	this.put("E474", "LATRONICO");
    	this.put("E475", "LATTARICO");
    	this.put("E476", "LAUCO");
    	this.put("E479", "LAUREANA DI BORRELLO");
    	this.put("E480", "LAUREANA CILENTO");
    	this.put("E481", "LAUREGNO .LAUREIN.");
    	this.put("E482", "LAURENZANA");
    	this.put("E483", "LAURIA");
    	this.put("E484", "LAURIANO");
    	this.put("E485", "LAURINO");
    	this.put("E486", "LAURITO");
    	this.put("E487", "LAURO");
    	this.put("E488", "LAVAGNA");
    	this.put("E489", "LAVAGNO");
    	this.put("E490", "LA VALLE AGORDINA");
    	this.put("E491", "LA VALLE .WENGEN.");
    	this.put("E492", "LAVARONE");
    	this.put("E493", "LAVELLO");
    	this.put("E494", "LAVENA PONTE TRESA");
    	this.put("E496", "LAVENO-MOMBELLO");
    	this.put("E497", "LAVENONE");
    	this.put("E498", "LAVIANO");
    	this.put("E500", "LAVIS");
    	this.put("E502", "LAZISE");
    	this.put("E504", "LAZZATE");
    	this.put("E505", "LECCE NEI MARSI");
    	this.put("E506", "LECCE");
    	this.put("E507", "LECCO");
    	this.put("E509", "LEFFE");
    	this.put("E510", "LEGGIUNO");
    	this.put("E512", "LEGNAGO");
    	this.put("E514", "LEGNANO");
    	this.put("E515", "LEGNARO");
    	this.put("E517", "LEI");
    	this.put("E518", "LEINI");
    	this.put("E519", "LEIVI");
    	this.put("E520", "LEMIE");
    	this.put("E522", "LENDINARA");
    	this.put("E523", "LENI");
    	this.put("E524", "LENNA");
    	this.put("E525", "LENNO");
    	this.put("E526", "LENO");
    	this.put("E527", "LENOLA");
    	this.put("E528", "LENTA");
    	this.put("E529", "OSMATE");
    	this.put("E530", "LENTATE SUL SEVESO");
    	this.put("E531", "LENTELLA");
    	this.put("E532", "LENTINI");
    	this.put("E535", "LEONESSA");
    	this.put("E536", "LEONFORTE");
    	this.put("E537", "LEPORANO");
    	this.put("E538", "LEQUILE");
    	this.put("E539", "LEQUIO TANARO");
    	this.put("E540", "LEQUIO BERRIA");
    	this.put("E541", "LERCARA FRIDDI");
    	this.put("E542", "LERICI");
    	this.put("E543", "LERMA");
    	this.put("E544", "LESA");
    	this.put("E546", "LESEGNO");
    	this.put("E547", "LESIGNANO DE' BAGNI");
    	this.put("E548", "TERENZO");
    	this.put("E549", "LESINA");
    	this.put("E550", "LESMO");
    	this.put("E551", "LESSOLO");
    	this.put("E552", "LESSONA");
    	this.put("E553", "LESTIZZA");
    	this.put("E554", "LETINO");
    	this.put("E555", "LETOJANNI");
    	this.put("E557", "LETTERE");
    	this.put("E558", "LETTOMANOPPELLO");
    	this.put("E559", "LETTOPALENA");
    	this.put("E560", "LEVANTO");
    	this.put("E562", "LEVATE");
    	this.put("E563", "LEVERANO");
    	this.put("E564", "LEVICE");
    	this.put("E565", "LEVICO TERME");
    	this.put("E566", "LEVONE");
    	this.put("E569", "LEZZENO");
    	this.put("E570", "LIBERI");
    	this.put("E571", "LIBRIZZI");
    	this.put("E573", "LICATA");
    	this.put("E574", "LICCIANA NARDI");
    	this.put("E576", "LICENZA");
    	this.put("E578", "LICODIA EUBEA");
    	this.put("E581", "LIERNA");
    	this.put("E583", "LIGNANA");
    	this.put("E584", "LIGNANO SABBIADORO");
    	this.put("E585", "LIGONCHIO");
    	this.put("E586", "LIGOSULLO");
    	this.put("E587", "LILLIANES");
    	this.put("E588", "LIMANA");
    	this.put("E589", "LIMATOLA");
    	this.put("E590", "LIMBADI");
    	this.put("E591", "LIMBIATE");
    	this.put("E592", "LIMENA");
    	this.put("E593", "LIMIDO COMASCO");
    	this.put("E594", "LIMINA");
    	this.put("E596", "LIMONE SUL GARDA");
    	this.put("E597", "LIMONE PIEMONTE");
    	this.put("E599", "LIMOSANO");
    	this.put("E600", "LINAROLO");
    	this.put("E602", "LINGUAGLOSSA");
    	this.put("E605", "LIONI");
    	this.put("E606", "LIPARI");
    	this.put("E607", "LIPOMO");
    	this.put("E608", "LIRIO");
    	this.put("E610", "LISCATE");
    	this.put("E611", "LISCIA");
    	this.put("E613", "LISCIANO NICCONE");
    	this.put("E614", "LISIGNAGO");
    	this.put("E615", "LISIO");
    	this.put("E617", "LISSONE");
    	this.put("E618", "MILENA");
    	this.put("E620", "LIVERI");
    	this.put("E621", "LIVIGNO");
    	this.put("E622", "LIVINALLONGO DEL COL DI LANA");
    	this.put("E623", "LIVO");
    	this.put("E624", "LIVO");
    	this.put("E625", "LIVORNO");
    	this.put("E626", "LIVORNO FERRARIS");
    	this.put("E627", "LIVRAGA");
    	this.put("E629", "LIZZANELLO");
    	this.put("E630", "LIZZANO");
    	this.put("E632", "LOANO");
    	this.put("E633", "LOAZZOLO");
    	this.put("E635", "LOCANA");
    	this.put("E638", "LOCATE VARESINO");
    	this.put("E639", "LOCATE DI TRIULZI");
    	this.put("E640", "LOCATELLO");
    	this.put("E644", "LOCERI");
    	this.put("E645", "LOCOROTONDO");
    	this.put("E646", "LOCULI");
    	this.put("E647", "LODE'");
    	this.put("E648", "LODI");
    	this.put("E649", "LODINE");
    	this.put("E651", "LODI VECCHIO");
    	this.put("E652", "LODRINO");
    	this.put("E654", "LOGRATO");
    	this.put("E655", "LOIANO");
    	this.put("E656", "LOMAGNA");
    	this.put("E658", "LOMASO");
    	this.put("E659", "LOMAZZO");
    	this.put("E660", "LOMBARDORE");
    	this.put("E661", "LOMBRIASCO");
    	this.put("E662", "LOMELLO");
    	this.put("E664", "LONA LASES");
    	this.put("E665", "LONATE CEPPINO");
    	this.put("E666", "LONATE POZZOLO");
    	this.put("E667", "LONATO");
    	this.put("E668", "LONDA");
    	this.put("E669", "LONGANO");
    	this.put("E671", "LONGARE");
    	this.put("E672", "LONGARONE");
    	this.put("E673", "LONGHENA");
    	this.put("E674", "LONGI");
    	this.put("E675", "LONGIANO");
    	this.put("E677", "LONGOBARDI");
    	this.put("E678", "LONGOBUCCO");
    	this.put("E679", "LONGONE AL SEGRINO");
    	this.put("E680", "PORTO AZZURRO");
    	this.put("E681", "LONGONE SABINO");
    	this.put("E682", "LONIGO");
    	this.put("E683", "LORANZE'");
    	this.put("E684", "LOREGGIA");
    	this.put("E685", "LOREGLIA");
    	this.put("E687", "LORENZAGO DI CADORE");
    	this.put("E688", "LORENZANA");
    	this.put("E689", "LOREO");
    	this.put("E690", "LORETO");
    	this.put("E691", "LORETO APRUTINO");
    	this.put("E692", "LORIA");
    	this.put("E693", "LORO CIUFFENNA");
    	this.put("E694", "LORO PICENO");
    	this.put("E695", "LORSICA");
    	this.put("E698", "LOSINE");
    	this.put("E700", "LOTZORAI");
    	this.put("E704", "LOVERE");
    	this.put("E705", "LOVERO");
    	this.put("E706", "LOZIO");
    	this.put("E707", "LOZZA");
    	this.put("E708", "LOZZO DI CADORE");
    	this.put("E709", "LOZZO ATESTINO");
    	this.put("E711", "LOZZOLO");
    	this.put("E712", "LU");
    	this.put("E713", "LUBRIANO");
    	this.put("E714", "LUCCA SICULA");
    	this.put("E715", "LUCCA");
    	this.put("E716", "LUCERA");
    	this.put("E718", "LUCIGNANO");
    	this.put("E719", "LUCINASCO");
    	this.put("E722", "LUCITO");
    	this.put("E723", "LUCO DEI MARSI");
    	this.put("E724", "LUCOLI");
    	this.put("E726", "LUGAGNANO VAL D'ARDA");
    	this.put("E727", "LUGNACCO");
    	this.put("E729", "LUGNANO IN TEVERINA");
    	this.put("E730", "LUGO");
    	this.put("E731", "LUGO DI VICENZA");
    	this.put("E734", "LUINO");
    	this.put("E735", "LUISAGO");
    	this.put("E736", "LULA");
    	this.put("E737", "LUMARZO");
    	this.put("E738", "LUMEZZANE");
    	this.put("E742", "LUNAMATRONA");
    	this.put("E743", "LUNANO");
    	this.put("E745", "LUNGRO");
    	this.put("E746", "LUOGOSANO");
    	this.put("E747", "LUOGOSANTO");
    	this.put("E748", "LUPARA");
    	this.put("E749", "LURAGO D'ERBA");
    	this.put("E750", "LURAGO MARINONE");
    	this.put("E751", "LURANO");
    	this.put("E752", "LURAS");
    	this.put("E753", "LURATE CACCIVIO");
    	this.put("E754", "LUSCIANO");
    	this.put("E757", "LUSERNA");
    	this.put("E758", "LUSERNA SAN GIOVANNI");
    	this.put("E759", "LUSERNETTA");
    	this.put("E760", "LUSEVERA");
    	this.put("E761", "LUSIA");
    	this.put("E762", "LUSIANA");
    	this.put("E763", "LUSIGLIE'");
    	this.put("E764", "LUSON .LUESEN.");
    	this.put("E767", "LUSTRA");
    	this.put("E769", "LUVINATE");
    	this.put("E770", "LUZZANA");
    	this.put("E772", "LUZZARA");
    	this.put("E773", "LUZZI");
    	this.put("E775", "MACCAGNO");
    	this.put("E777", "MACCASTORNA");
    	this.put("E778", "MACCHIA D'ISERNIA");
    	this.put("E779", "MACCHIAGODENA");
    	this.put("E780", "MACCHIA VALFORTORE");
    	this.put("E782", "MACELLO");
    	this.put("E783", "MACERATA");
    	this.put("E784", "MACERATA CAMPANIA");
    	this.put("E785", "MACERATA FELTRIA");
    	this.put("E786", "MACHERIO");
    	this.put("E787", "MACLODIO");
    	this.put("E788", "MACOMER");
    	this.put("E789", "MACRA");
    	this.put("E790", "MACUGNAGA");
    	this.put("E791", "MADDALONI");
    	this.put("E793", "MADIGNANO");
    	this.put("E794", "MADONE");
    	this.put("E795", "MADONNA DEL SASSO");
    	this.put("E798", "MAENZA");
    	this.put("E799", "MAFALDA");
    	this.put("E800", "MAGASA");
    	this.put("E801", "MAGENTA");
    	this.put("E803", "MAGGIORA");
    	this.put("E804", "MAGHERNO");
    	this.put("E805", "MAGIONE");
    	this.put("E806", "MAGISANO");
    	this.put("E807", "MAGLIANO DI TENNA");
    	this.put("E808", "MAGLIANO ALPI");
    	this.put("E809", "MAGLIANO ALFIERI");
    	this.put("E810", "MAGLIANO IN TOSCANA");
    	this.put("E811", "MAGLIANO DE' MARSI");
    	this.put("E812", "MAGLIANO SABINA");
    	this.put("E813", "MAGLIANO ROMANO");
    	this.put("E814", "MAGLIANO VETERE");
    	this.put("E815", "MAGLIE");
    	this.put("E816", "MAGLIOLO");
    	this.put("E817", "MAGLIONE");
    	this.put("E818", "MAGNACAVALLO");
    	this.put("E819", "MAGNAGO");
    	this.put("E820", "MAGNANO IN RIVIERA");
    	this.put("E821", "MAGNANO");
    	this.put("E825", "MAGOMADAS");
    	this.put("E829", "MAGRE' SULLA STRADA DEL VINO .MARGREID AN DE.");
    	this.put("E830", "MAGREGLIO");
    	this.put("E833", "MAJANO");
    	this.put("E834", "MAIDA");
    	this.put("E835", "MAIERA'");
    	this.put("E836", "MAIERATO");
    	this.put("E837", "MAIOLATI SPONTINI");
    	this.put("E838", "MAIOLO");
    	this.put("E839", "MAIORI");
    	this.put("E840", "MAIRAGO");
    	this.put("E841", "MAIRANO");
    	this.put("E842", "MAISSANA");
    	this.put("E843", "MALAGNINO");
    	this.put("E844", "MALALBERGO");
    	this.put("E847", "MALBORGHETTO-VALBRUNA");
    	this.put("E848", "MALCESINE");
    	this.put("E850", "MALE'");
    	this.put("E851", "MALEGNO");
    	this.put("E852", "MALEO");
    	this.put("E853", "MALESCO");
    	this.put("E854", "MALETTO");
    	this.put("E855", "MALFA");
    	this.put("E856", "MALGESSO");
    	this.put("E858", "MALGRATE");
    	this.put("E859", "MALITO");
    	this.put("E860", "MALLARE");
    	this.put("E862", "MALLES VENOSTA .MALS.");
    	this.put("E863", "MALNATE");
    	this.put("E864", "MALO");
    	this.put("E865", "MALONNO");
    	this.put("E866", "MALOSCO");
    	this.put("E868", "MALTIGNANO");
    	this.put("E869", "MALVAGNA");
    	this.put("E870", "MALVICINO");
    	this.put("E872", "MALVITO");
    	this.put("E873", "MAMMOLA");
    	this.put("E874", "MAMOIADA");
    	this.put("E875", "MANCIANO");
    	this.put("E876", "MANDANICI");
    	this.put("E877", "MANDAS");
    	this.put("E878", "MANDATORICCIO");
    	this.put("E879", "MANDELLO DEL LARIO");
    	this.put("E880", "MANDELLO VITTA");
    	this.put("E882", "MANDURIA");
    	this.put("E883", "MANERBA DEL GARDA");
    	this.put("E884", "MANERBIO");
    	this.put("E885", "MANFREDONIA");
    	this.put("E887", "MANGO");
    	this.put("E888", "MANGONE");
    	this.put("E889", "MANIAGO");
    	this.put("E891", "MANOCALZATI");
    	this.put("E892", "MANOPPELLO");
    	this.put("E893", "MANSUE'");
    	this.put("E894", "MANTA");
    	this.put("E896", "MANTELLO");
    	this.put("E897", "MANTOVA");
    	this.put("E899", "MANZANO");
    	this.put("E900", "MANZIANA");
    	this.put("E901", "MAPELLO");
    	this.put("E902", "MARA");
    	this.put("E903", "MARACALAGONIS");
    	this.put("E904", "MARANELLO");
    	this.put("E905", "MARANO SUL PANARO");
    	this.put("E906", "MARANO DI NAPOLI");
    	this.put("E907", "MARANO TICINO");
    	this.put("E908", "MARANO EQUO");
    	this.put("E910", "MARANO LAGUNARE");
    	this.put("E911", "MARANO DI VALPOLICELLA");
    	this.put("E912", "MARANO VICENTINO");
    	this.put("E914", "MARANO MARCHESATO");
    	this.put("E915", "MARANO PRINCIPATO");
    	this.put("E917", "MARANZANA");
    	this.put("E919", "MARATEA");
    	this.put("E921", "MARCALLO CON CASONE");
    	this.put("E922", "MARCARIA");
    	this.put("E923", "MARCEDUSA");
    	this.put("E924", "MARCELLINA");
    	this.put("E925", "MARCELLINARA");
    	this.put("E927", "MARCETELLI");
    	this.put("E928", "MARCHENO");
    	this.put("E929", "MARCHIROLO");
    	this.put("E930", "MARCIANA");
    	this.put("E931", "MARCIANA MARINA");
    	this.put("E932", "MARCIANISE");
    	this.put("E933", "MARCIANO DELLA CHIANA");
    	this.put("E934", "MARCIGNAGO");
    	this.put("E936", "MARCON");
    	this.put("E938", "MAREBBE .ENNEBERG.");
    	this.put("E939", "MARENE");
    	this.put("E940", "MARENO DI PIAVE");
    	this.put("E941", "MARENTINO");
    	this.put("E944", "MARETTO");
    	this.put("E945", "MARGARITA");
    	this.put("E946", "MARGHERITA DI SAVOIA");
    	this.put("E947", "MARGNO");
    	this.put("E949", "MARIANA MANTOVANA");
    	this.put("E951", "MARIANO COMENSE");
    	this.put("E952", "MARIANO DEL FRIULI");
    	this.put("E953", "MARIANOPOLI");
    	this.put("E954", "MARIGLIANELLA");
    	this.put("E955", "MARIGLIANO");
    	this.put("E956", "MARINA DI GIOIOSA IONICA");
    	this.put("E957", "MARINEO");
    	this.put("E958", "MARINO");
    	this.put("E959", "MARLENGO .MARLING.");
    	this.put("E960", "MARLIANA");
    	this.put("E961", "MARMENTINO");
    	this.put("E962", "MARMIROLO");
    	this.put("E963", "MARMORA");
    	this.put("E965", "MARNATE");
    	this.put("E967", "MARONE");
    	this.put("E968", "MAROPATI");
    	this.put("E970", "MAROSTICA");
    	this.put("E971", "MARRADI");
    	this.put("E972", "MARRUBIU");
    	this.put("E973", "MARSAGLIA");
    	this.put("E974", "MARSALA");
    	this.put("E975", "MARSCIANO");
    	this.put("E976", "MARSICO NUOVO");
    	this.put("E977", "MARSICOVETERE");
    	this.put("E978", "MARTA");
    	this.put("E979", "MARTANO");
    	this.put("E980", "MARTELLAGO");
    	this.put("E981", "MARTELLO .MARTELL.");
    	this.put("E982", "MARTIGNACCO");
    	this.put("E983", "MARTIGNANA DI PO");
    	this.put("E984", "MARTIGNANO");
    	this.put("E986", "MARTINA FRANCA");
    	this.put("E987", "MARTINENGO");
    	this.put("E988", "MARTINIANA PO");
    	this.put("E989", "MARTINSICURO");
    	this.put("E990", "MARTIRANO");
    	this.put("E991", "MARTIRANO LOMBARDO");
    	this.put("E992", "MARTIS");
    	this.put("E993", "MARTONE");
    	this.put("E994", "MARUDO");
    	this.put("E995", "MARUGGIO");
    	this.put("E997", "MARZANO DI NOLA");
    	this.put("E998", "MARZANO APPIO");
    	this.put("E999", "MARZANO");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
