package cities_codes;

import java.util.HashMap;

@SuppressWarnings("serial")
public class CitiesCodes_M extends HashMap<String, String> {

    public CitiesCodes_M(){
    	this.put("M002", "VILLARBASSE");
    	this.put("M003", "VILLARBOIT");
    	this.put("M004", "VILLAREGGIA");
    	this.put("M006", "VILLA RENDENA");
    	this.put("M007", "VILLAR FOCCHIARDO");
    	this.put("M009", "VILLAROMAGNANO");
    	this.put("M011", "VILLAROSA");
    	this.put("M013", "VILLAR PELLICE");
    	this.put("M014", "VILLAR PEROSA");
    	this.put("M015", "VILLAR SAN COSTANZO");
    	this.put("M016", "VILLASALTO");
    	this.put("M017", "VILLASANTA");
    	this.put("M018", "VILLA SAN GIOVANNI");
    	this.put("M019", "VILLA SAN SECONDO");
    	this.put("M021", "VILLA SANTA LUCIA DEGLI ABRUZZI");
    	this.put("M022", "VILLA SANTA MARIA");
    	this.put("M023", "VILLA SANT'ANGELO");
    	this.put("M025", "VILLASOR");
    	this.put("M026", "VILLASPECIOSA");
    	this.put("M027", "VILLASTELLONE");
    	this.put("M028", "VILLATA");
    	this.put("M030", "VILLAURBANA");
    	this.put("M031", "VILLAVALLELONGA");
    	this.put("M032", "VILLAVERLA");
    	this.put("M034", "VILLA VICENTINA");
    	this.put("M041", "VILLETTA BARREA");
    	this.put("M042", "VILLETTE");
    	this.put("M043", "VILLESSE");
    	this.put("M044", "VILLIMPENTA");
    	this.put("M045", "VILLONGO");
    	this.put("M048", "VILLORBA");
    	this.put("M050", "VILMINORE DI SCALVE");
    	this.put("M052", "VIMERCATE");
    	this.put("M053", "VIMODRONE");
    	this.put("M055", "VINADIO");
    	this.put("M057", "VINCHIATURO");
    	this.put("M058", "VINCHIO");
    	this.put("M059", "VINCI");
    	this.put("M060", "VINOVO");
    	this.put("M062", "VINZAGLIO");
    	this.put("M063", "VIOLA");
    	this.put("M065", "VIONE");
    	this.put("M067", "VIPITENO .STERZING.");
    	this.put("M069", "VIRLE PIEMONTE");
    	this.put("M070", "VISANO");
    	this.put("M071", "VISCHE");
    	this.put("M072", "VISCIANO");
    	this.put("M073", "VISCO");
    	this.put("M077", "VISONE");
    	this.put("M078", "VISSO");
    	this.put("M079", "VISTARINO");
    	this.put("M080", "VISTRORIO");
    	this.put("M081", "VITA");
    	this.put("M082", "VITERBO");
    	this.put("M083", "VITICUSO");
    	this.put("M085", "VITO D'ASIO");
    	this.put("M086", "VITORCHIANO");
    	this.put("M088", "VITTORIA");
    	this.put("M089", "VITTORIO VENETO");
    	this.put("M090", "VITTORITO");
    	this.put("M091", "VITTUONE");
    	this.put("M092", "VITULAZIO");
    	this.put("M093", "VITULANO");
    	this.put("M094", "VIU'");
    	this.put("M095", "VIVARO ROMANO");
    	this.put("M096", "VIVARO");
    	this.put("M098", "VIVERONE");
    	this.put("M100", "VIZZINI");
    	this.put("M101", "VIZZOLA TICINO");
    	this.put("M102", "VIZZOLO PREDABISSI");
    	this.put("M103", "VO'");
    	this.put("M104", "VOBARNO");
    	this.put("M105", "VOBBIA");
    	this.put("M106", "VOCCA");
    	this.put("M108", "VODO CADORE");
    	this.put("M109", "VOGHERA");
    	this.put("M110", "VOGHIERA");
    	this.put("M111", "VOGOGNA");
    	this.put("M113", "VOLANO");
    	this.put("M115", "VOLLA");
    	this.put("M116", "VOLONGO");
    	this.put("M118", "VOLPAGO DEL MONTELLO");
    	this.put("M119", "VOLPARA");
    	this.put("M120", "VOLPEDO");
    	this.put("M121", "VOLPEGLINO");
    	this.put("M122", "VOLPIANO");
    	this.put("M123", "VOLTAGGIO");
    	this.put("M124", "VOLTAGO AGORDINO");
    	this.put("M125", "VOLTA MANTOVANA");
    	this.put("M126", "VOLTERRA");
    	this.put("M127", "VOLTIDO");
    	this.put("M130", "VOLTURARA IRPINA");
    	this.put("M131", "VOLTURARA APPULA");
    	this.put("M132", "VOLTURINO");
    	this.put("M133", "VOLVERA");
    	this.put("M136", "VOTTIGNASCO");
    	this.put("M138", "ZACCANOPOLI");
    	this.put("M139", "ZAFFERANA ETNEA");
    	this.put("M140", "ZAGARISE");
    	this.put("M141", "ZAGAROLO");
    	this.put("M142", "ZAMBANA");
    	this.put("M143", "ZAMBRONE");
    	this.put("M144", "ZANDOBBIO");
    	this.put("M145", "ZANE'");
    	this.put("M147", "ZANICA");
    	this.put("M150", "ZAVATTARELLO");
    	this.put("M152", "ZECCONE");
    	this.put("M153", "ZEDDIANI");
    	this.put("M156", "ZELBIO");
    	this.put("M158", "ZELO BUON PERSICO");
    	this.put("M160", "ZELO SURRIGONE");
    	this.put("M161", "ZEME");
    	this.put("M162", "ZENEVREDO");
    	this.put("M163", "ZENSON DI PIAVE");
    	this.put("M165", "ZERBA");
    	this.put("M166", "ZERBO");
    	this.put("M167", "ZERBOLO'");
    	this.put("M168", "ZERFALIU");
    	this.put("M169", "ZERI");
    	this.put("M170", "ZERMEGHEDO");
    	this.put("M171", "ZERO BRANCO");
    	this.put("M172", "ZEVIO");
    	this.put("M173", "ZIANO DI FIEMME");
    	this.put("M174", "ZIBELLO");
    	this.put("M176", "ZIBIDO SAN GIACOMO");
    	this.put("M177", "ZIGNAGO");
    	this.put("M178", "ZIMELLA");
    	this.put("M179", "ZIMONE");
    	this.put("M180", "ZINASCO");
    	this.put("M182", "ZOAGLI");
    	this.put("M183", "ZOCCA");
    	this.put("M184", "ZOGNO");
    	this.put("M185", "ZOLA PREDOSA");
    	this.put("M187", "ZOLLINO");
    	this.put("M188", "ZONE");
    	this.put("M189", "ZOPPE' DI CADORE");
    	this.put("M190", "ZOPPOLA");
    	this.put("M194", "ZOVENCEDO");
    	this.put("M196", "ZUBIENA");
    	this.put("M197", "ZUCCARELLO");
    	this.put("M198", "ZUCLO");
    	this.put("M199", "ZUGLIANO");
    	this.put("M200", "ZUGLIO");
    	this.put("M201", "ZUMAGLIA");
    	this.put("M202", "ZUMPANO");
    	this.put("M203", "ZUNGOLI");
    	this.put("M204", "ZUNGRI");
    	this.put("M207", "LARIANO");
    	this.put("M208", "LAMEZIA TERME");
    	this.put("M209", "SANT'ANNA ARRESI");
    	this.put("M210", "TERME VIGLIATORE");
    	this.put("M211", "ACQUEDOLCI");
    	this.put("M212", "LADISPOLI");
    	this.put("M213", "ARDEA");
    	this.put("M214", "BADESI");
    	this.put("M253", "SICIGNANO DEGLI ALBURNI");
    	this.put("M255", "MOLINA ATERNO");
    	this.put("M256", "SCANZANO JONICO");
    	this.put("M257", "PORTOPALO DI CAPO PASSERO");
    	this.put("M258", "AVIGLIANO UMBRO");
    	this.put("M259", "VIDDALBA");
    	this.put("M260", "CASAPESENNA");
    	this.put("M261", "CASTRO");
    	this.put("M262", "CELLOLE");
    	this.put("M263", "PORTO CESAREO");
    	this.put("M264", "SAN CASSIANO");
    	this.put("M265", "VAJONT");
    	this.put("M266", "ORDONA");
    	this.put("M267", "ZAPPONETA");
    	this.put("M268", "BLUFI");
    	this.put("M269", "PATERNO");
    	this.put("M270", "MASAINAS");
    	this.put("M271", "MAZZARRONE");
    	this.put("M272", "CIAMPINO");
    	this.put("M273", "SANTA MARIA LA CARITA'");
    	this.put("M274", "GOLFO ARANCI");
    	this.put("M275", "LOIRI PORTO SAN PAOLO");
    	this.put("M276", "SANT'ANTONIO DI GALLURA");
    	this.put("M277", "SAN FERDINANDO");
    	this.put("M278", "VILLAPERUCCIO");
    	this.put("M279", "PRIOLO GARGALLO");
    	this.put("M280", "TRECASE");
    	this.put("M281", "PETROSINO");
    	this.put("M282", "TERGU");
    	this.put("M283", "MANIACE");
    	this.put("M284", "SANTA MARIA COGHINAS");
    	this.put("M285", "CARDEDU");
    	this.put("M286", "TORRENOVA");
    	this.put("M287", "RAGALNA");
    	this.put("M288", "CASTIADAS");
    	this.put("M289", "MASSA DI SOMMA");
    	this.put("M290", "STINTINO");
    	this.put("M291", "PISCINAS");
    	this.put("M292", "ERULA");
    	this.put("M294", "BELLIZZI");
    	this.put("M295", "SAN CESAREO");
    	this.put("M297", "FIUMICINO");
    	this.put("M298", "STATTE");
    	this.put("M300", "DUE CARRARE");
    	this.put("M301", "PADRU");
    	this.put("M302", "MONTIGLIO MONFERRATO");
    	this.put("M303", "RONZO-CHIENIS");
    	this.put("M304", "MOSSO");
    	this.put("M308", "CAVALLINO-TREPORTI");
    	this.put("M309", "FONTE NUOVA");
    	this.put("M311", "CAMPOLONGO TAPOGLIANO");
    	this.put("M312", "LONATO DEL GARDA");
    	this.put("M313", "LEDRO");
    	this.put("M314", "COMANO TERME");
    	this.put("M315", "GRAVEDONA ED UNITI");
    	this.put("M316", "MAPPANO");
    	this.put("M317", "RIVIGNANO TEOR");
    	this.put("M318", "TRECASTELLI");
    	this.put("M319", "FABBRICHE DI VERGEMOLI");
    	this.put("M320", "VALSAMOGGIA");
    	this.put("M321", "FIGLINE E INCISA VALDARNO");
    	this.put("M322", "CASTELFRANCO PIANDISCO'");
    	this.put("M323", "FISCAGLIA");
    	this.put("M324", "POGGIO TORRIANA");
    	this.put("M325", "SISSA TRECASALI");
    	this.put("M326", "SCARPERIA E SAN PIERO");
    	this.put("M327", "CASCIANA TERME LARI");
    	this.put("M328", "CRESPINA LORENZANA");
    	this.put("M329", "PRATOVECCHIO STIA");
    	this.put("M330", "MONTORO");
    	this.put("M331", "VALLEFOGLIA");
    	this.put("M332", "QUERO VAS");
    	this.put("M333", "SANT'OMOBONO TERME");
    	this.put("M334", "VAL BREMBILLA");
    	this.put("M335", "BELLAGIO");
    	this.put("M336", "COLVERDE");
    	this.put("M337", "VERDERIO");
    	this.put("M338", "CORNALE E BASTIDA");
    	this.put("M339", "MACCAGNO CON PINO E VEDDASCA");
    	this.put("M340", "BORGO VIRGILIO");
    	this.put("M341", "TREMEZZINA");
    	this.put("M342", "LONGARONE");
    	this.put("M343", "VALDAONE");
    	this.put("M344", "PREDAIA");
    	this.put("M345", "SAN LORENZO DORSINO");
    	this.put("M346", "VALVASONE ARZENE");
    	this.put("M347", "SILLANO GIUNCUGNANO");
    	this.put("M348", "LA VALLETTA BRIANZA");
    	this.put("M349", "ALTAVALLE");
    	this.put("M350", "ALTOPIANO DELLA VIGOLANA");
    	this.put("M351", "AMBLAR-DON");
    	this.put("M352", "BORGO CHIESE");
    	this.put("M353", "BORGO LARES");
    	this.put("M354", "CASTEL IVANO");
    	this.put("M355", "CEMBRA LISIGNAGO");
    	this.put("M356", "CONTA'");
    	this.put("M357", "MADRUZZO");
    	this.put("M358", "PORTE DI RENDENA");
    	this.put("M359", "PRIMIERO SAN MARTINO DI CASTROZZA");
    	this.put("M360", "SELLA GIUDICARIE");
    	this.put("M361", "TRE VILLE");
    	this.put("M362", "VALLELAGHI");
    	this.put("M363", "VILLE D'ANAUNIA");
    	this.put("M364", "VENTASSO");
    	this.put("M365", "PIEVE DI BONO-PREZZO");
    	this.put("M366", "DIMARO FOLGARIDA");
    	this.put("M367", "POLESINE ZIBELLO");
    	this.put("M368", "MONTESCUDO-MONTE COLOMBO");
    	this.put("M369", "ALTO RENO TERME");
    	this.put("M370", "BORGOMEZZAVALLE");
    	this.put("M371", "LESSONA");
    	this.put("M372", "CORTEOLONA E GENZONE");
    	this.put("M373", "CAMPIGLIA CERVO");
    	this.put("M374", "VAL DI ZOLDO");
    	this.put("M375", "ALPAGO");
    	this.put("M376", "ABETONE CUTIGLIANO");
    	this.put("M377", "SAN MARCELLO PITEGLIO");
    	this.put("M378", "MONTALCINO");
    	this.put("M379", "TERRE ROVERESCHE");
    	this.put("M380", "COLLI AL METAURO");
    	this.put("M381", "TERRE DEL RENO");
    	this.put("M382", "VALFORNACE");
    	this.put("M383", "ALTA VALLE INTELVI");
    	this.put("M384", "VAL LIONA");
    	this.put("M385", "CASALI DEL MANCO");
    	this.put("M386", "ALTA VAL TIDONE");
    	this.put("M387", "MONTALTO CARPASIO");
    	this.put("M388", "CASSANO SPINOLA");
    	this.put("M389", "ALTO SERMENZA");
    	this.put("M390", "SAN GIOVANNI DI FASSA-SEN JAN");
    	this.put("M391", "RIO");
    	this.put("M392", "LATERINA PERGINE VALDARNO");
    	this.put("M393", "CASTELGERUNDO");
    	this.put("M394", "CENTRO VALLE INTELVI");
    	this.put("M395", "VALVARRONE");
    	this.put("M396", "BORGO MANTOVANO");
    	this.put("M397", "ALLUVIONI PIOVERA");
    	this.put("M398", "CELLIO CON BREIA");
    	this.put("M399", "TREPPO LIGOSULLO");
    	this.put("M400", "FIUMICELLO VILLA VICENTINA");
    	this.put("M401", "BARBARANO MOSSANO");
    	this.put("M402", "BORGO VENETO");
    	this.put("M403", "CORIGLIANO-ROSSANO");
    	this.put("M404", "VALLE CANNOBINA");
    	this.put("M405", "VAL DI CHY");
    	this.put("M406", "BORGOCARBONARA");
    	this.put("M407", "TERRE D'ADIGE");
    	this.put("M408", "BARBERINO TAVARNELLE");
    	this.put("M409", "TRESIGNANA");
    	this.put("M410", "RIVA DEL PO");
    	this.put("M411", "SORBOLO MEZZANI");
    	this.put("M412", "SOLBIATE CON CAGNO");
    	this.put("M413", "SASSOCORVARO AUDITORE");
    	this.put("M414", "QUAREGNA CERRETO");
    	this.put("M415", "VALCHIUSA");
    	this.put("M416", "GATTICO-VERUNO");
    	this.put("M417", "VALDILANA");
    	this.put("M418", "PIADENA DRIZZONA");
    	this.put("M419", "COLLI VERDI");
    	this.put("M420", "LU E CUCCARO MONFERRATO");
    	this.put("M421", "BORGO VALBELLUNA");
    	this.put("M422", "PIEVE DEL GRAPPA");
    	this.put("M423", "VALBRENTA");
    	this.put("M424", "VERMEZZO CON ZELO");
    	this.put("M425", "CADREZZATE CON OSMATE");
    	this.put("M426", "COLCERESA");
    	this.put("M427", "LUSIANA CONCO");
    	this.put("M428", "PRESICCE-ACQUARICA");
    	this.put("M429", "BORGO D'ANAUNIA");
    	this.put("M430", "NOVELLA");
    	this.put("M431", "VILLE DI FIEMME");
    	this.put("M432", "MISILISCEMI");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
