package cities_codes;

import java.util.HashMap;

@SuppressWarnings("serial")
public class CitiesCodes_G extends HashMap<String, String> {

    public CitiesCodes_G(){
    	this.put("G001", "ODOLO");
    	this.put("G002", "OFENA");
    	this.put("G003", "OFFAGNA");
    	this.put("G004", "OFFANENGO");
    	this.put("G005", "OFFIDA");
    	this.put("G006", "OFFLAGA");
    	this.put("G007", "OGGEBBIO");
    	this.put("G008", "OGGIONA CON SANTO STEFANO");
    	this.put("G009", "OGGIONO");
    	this.put("G010", "OGLIANICO");
    	this.put("G011", "OGLIASTRO CILENTO");
    	this.put("G012", "OYACE");
    	this.put("G015", "OLBIA");
    	this.put("G016", "OLCENENGO");
    	this.put("G018", "OLDENICO");
    	this.put("G019", "OLEGGIO");
    	this.put("G020", "OLEGGIO CASTELLO");
    	this.put("G021", "OLEVANO DI LOMELLINA");
    	this.put("G022", "OLEVANO ROMANO");
    	this.put("G023", "OLEVANO SUL TUSCIANO");
    	this.put("G025", "OLGIATE COMASCO");
    	this.put("G026", "OLGIATE MOLGORA");
    	this.put("G028", "OLGIATE OLONA");
    	this.put("G030", "OLGINATE");
    	this.put("G031", "OLIENA");
    	this.put("G032", "OLIVA GESSI");
    	this.put("G034", "OLIVADI");
    	this.put("G036", "OLIVERI");
    	this.put("G037", "OLIVETO LUCANO");
    	this.put("G039", "OLIVETO CITRA");
    	this.put("G040", "OLIVETO LARIO");
    	this.put("G041", "OLIVETTA SAN MICHELE");
    	this.put("G042", "OLIVOLA");
    	this.put("G043", "OLLASTRA");
    	this.put("G044", "OLLOLAI");
    	this.put("G045", "OLLOMONT");
    	this.put("G046", "OLMEDO");
    	this.put("G047", "OLMENETA");
    	this.put("G048", "OLMO GENTILE");
    	this.put("G049", "OLMO AL BREMBO");
    	this.put("G050", "OLTRE IL COLLE");
    	this.put("G054", "OLTRESSENDA ALTA");
    	this.put("G056", "OLTRONA DI SAN MAMETTE");
    	this.put("G058", "OLZAI");
    	this.put("G061", "OME");
    	this.put("G062", "OMEGNA");
    	this.put("G063", "OMIGNANO");
    	this.put("G064", "ONANI'");
    	this.put("G065", "ONANO");
    	this.put("G066", "ONCINO");
    	this.put("G068", "ONETA");
    	this.put("G070", "ONIFAI");
    	this.put("G071", "ONIFERI");
    	this.put("G074", "ONO SAN PIETRO");
    	this.put("G075", "ONORE");
    	this.put("G076", "ONZO");
    	this.put("G078", "OPERA");
    	this.put("G079", "OPI");
    	this.put("G080", "OPPEANO");
    	this.put("G081", "OPPIDO LUCANO");
    	this.put("G082", "OPPIDO MAMERTINA");
    	this.put("G083", "ORA .AUER.");
    	this.put("G084", "ORANI");
    	this.put("G086", "ORATINO");
    	this.put("G087", "ORBASSANO");
    	this.put("G088", "ORBETELLO");
    	this.put("G089", "ORCIANO DI PESARO");
    	this.put("G090", "ORCIANO PISANO");
    	this.put("G093", "ORERO");
    	this.put("G095", "ORGIANO");
    	this.put("G096", "PIEVE FISSIRAGA");
    	this.put("G097", "ORGOSOLO");
    	this.put("G098", "ORIA");
    	this.put("G102", "ORICOLA");
    	this.put("G103", "ORIGGIO");
    	this.put("G105", "ORINO");
    	this.put("G107", "ORIO LITTA");
    	this.put("G108", "ORIO AL SERIO");
    	this.put("G109", "ORIO CANAVESE");
    	this.put("G110", "ORIOLO");
    	this.put("G111", "ORIOLO ROMANO");
    	this.put("G113", "ORISTANO");
    	this.put("G114", "ORMEA");
    	this.put("G115", "ORMELLE");
    	this.put("G116", "ORNAGO");
    	this.put("G117", "ORNAVASSO");
    	this.put("G118", "ORNICA");
    	this.put("G119", "OROSEI");
    	this.put("G120", "OROTELLI");
    	this.put("G121", "ORRIA");
    	this.put("G122", "ORROLI");
    	this.put("G123", "ORSAGO");
    	this.put("G124", "ORSARA BORMIDA");
    	this.put("G125", "ORSARA DI PUGLIA");
    	this.put("G126", "ORSENIGO");
    	this.put("G128", "ORSOGNA");
    	this.put("G129", "ORSOMARSO");
    	this.put("G130", "ORTA DI ATELLA");
    	this.put("G131", "ORTA NOVA");
    	this.put("G133", "ORTACESUS");
    	this.put("G134", "ORTA SAN GIULIO");
    	this.put("G135", "ORTE");
    	this.put("G136", "ORTELLE");
    	this.put("G137", "ORTEZZANO");
    	this.put("G139", "ORTIGNANO RAGGIOLO");
    	this.put("G140", "ORTISEI .ST ULRICH.");
    	this.put("G141", "ORTONA");
    	this.put("G142", "ORTONA DEI MARSI");
    	this.put("G143", "LUNI");
    	this.put("G144", "ORTOVERO");
    	this.put("G145", "ORTUCCHIO");
    	this.put("G146", "ORTUERI");
    	this.put("G147", "ORUNE");
    	this.put("G148", "ORVIETO");
    	this.put("G149", "ORZINUOVI");
    	this.put("G150", "ORZIVECCHI");
    	this.put("G151", "OSASCO");
    	this.put("G152", "OSASIO");
    	this.put("G153", "OSCHIRI");
    	this.put("G154", "OSIDDA");
    	this.put("G155", "OSIGLIA");
    	this.put("G156", "OSILO");
    	this.put("G157", "OSIMO");
    	this.put("G158", "OSINI");
    	this.put("G159", "OSIO SOPRA");
    	this.put("G160", "OSIO SOTTO");
    	this.put("G161", "OSNAGO");
    	this.put("G163", "OSOPPO");
    	this.put("G164", "OSPEDALETTI");
    	this.put("G165", "OSPEDALETTO D'ALPINOLO");
    	this.put("G166", "OSPEDALETTO LODIGIANO");
    	this.put("G167", "OSPEDALETTO EUGANEO");
    	this.put("G168", "OSPEDALETTO");
    	this.put("G169", "OSPITALE DI CADORE");
    	this.put("G170", "OSPITALETTO");
    	this.put("G171", "OSSAGO LODIGIANO");
    	this.put("G173", "OSSANA");
    	this.put("G178", "OSSI");
    	this.put("G179", "OSSIMO");
    	this.put("G181", "OSSONA");
    	this.put("G182", "OSSUCCIO");
    	this.put("G183", "OSTANA");
    	this.put("G184", "OSTELLATO");
    	this.put("G185", "OSTIANO");
    	this.put("G186", "OSTIGLIA");
    	this.put("G187", "OSTUNI");
    	this.put("G188", "OTRANTO");
    	this.put("G189", "OTRICOLI");
    	this.put("G190", "OTTAVIANO");
    	this.put("G191", "OTTANA");
    	this.put("G192", "OTTATI");
    	this.put("G193", "OTTIGLIO");
    	this.put("G194", "OTTOBIANO");
    	this.put("G195", "OTTONE");
    	this.put("G196", "OULX");
    	this.put("G197", "OVADA");
    	this.put("G198", "OVARO");
    	this.put("G199", "OVIGLIO");
    	this.put("G200", "OVINDOLI");
    	this.put("G201", "OVODDA");
    	this.put("G202", "OZEGNA");
    	this.put("G203", "OZIERI");
    	this.put("G204", "OZZANO MONFERRATO");
    	this.put("G205", "OZZANO DELL'EMILIA");
    	this.put("G206", "OZZERO");
    	this.put("G207", "PABILLONIS");
    	this.put("G208", "PACECO");
    	this.put("G209", "PACE DEL MELA");
    	this.put("G210", "PACENTRO");
    	this.put("G211", "PACHINO");
    	this.put("G212", "PACIANO");
    	this.put("G213", "PADENGHE SUL GARDA");
    	this.put("G214", "PADERGNONE");
    	this.put("G215", "PADERNA");
    	this.put("G217", "PADERNO FRANCIACORTA");
    	this.put("G218", "PADERNO D'ADDA");
    	this.put("G220", "PADERNO DUGNANO");
    	this.put("G221", "PADERNO DEL GRAPPA");
    	this.put("G222", "PADERNO PONCHIELLI");
    	this.put("G223", "ROBBIATE");
    	this.put("G224", "PADOVA");
    	this.put("G225", "PADRIA");
    	this.put("G226", "PADULA");
    	this.put("G227", "PADULI");
    	this.put("G228", "PAESANA");
    	this.put("G229", "PAESE");
    	this.put("G230", "PAGANI");
    	this.put("G232", "PAGANICO SABINO");
    	this.put("G233", "PAGAZZANO");
    	this.put("G234", "PAGLIARA");
    	this.put("G237", "PAGLIETA");
    	this.put("G238", "PAGNACCO");
    	this.put("G240", "PAGNO");
    	this.put("G241", "PAGNONA");
    	this.put("G242", "PAGO DEL VALLO DI LAURO");
    	this.put("G243", "PAGO VEIANO");
    	this.put("G247", "PAISCO LOVENO");
    	this.put("G248", "PAITONE");
    	this.put("G249", "PALADINA");
    	this.put("G250", "PALAGANO");
    	this.put("G251", "PALAGIANELLO");
    	this.put("G252", "PALAGIANO");
    	this.put("G253", "PALAGONIA");
    	this.put("G254", "PALAIA");
    	this.put("G255", "PALANZANO");
    	this.put("G257", "PALATA");
    	this.put("G258", "PALAU");
    	this.put("G259", "PALAZZAGO");
    	this.put("G260", "PALAZZO PIGNANO");
    	this.put("G261", "PALAZZO SAN GERVASIO");
    	this.put("G262", "PALAZZO CANAVESE");
    	this.put("G263", "PALAZZO ADRIANO");
    	this.put("G264", "PALAZZOLO SULL'OGLIO");
    	this.put("G266", "PALAZZOLO VERCELLESE");
    	this.put("G267", "PALAZZOLO ACREIDE");
    	this.put("G268", "PALAZZOLO DELLO STELLA");
    	this.put("G270", "PALAZZUOLO SUL SENIO");
    	this.put("G271", "PALENA");
    	this.put("G272", "PALERMITI");
    	this.put("G273", "PALERMO");
    	this.put("G274", "PALESTRINA");
    	this.put("G275", "PALESTRO");
    	this.put("G276", "PALIANO");
    	this.put("G277", "PALIZZI");
    	this.put("G278", "PALLAGORIO");
    	this.put("G280", "PALLANZENO");
    	this.put("G281", "PALLARE");
    	this.put("G282", "PALMA DI MONTECHIARO");
    	this.put("G283", "PALMA CAMPANIA");
    	this.put("G284", "PALMANOVA");
    	this.put("G285", "PALMARIGGI");
    	this.put("G286", "PALMAS ARBOREA");
    	this.put("G287", "SAN GIOVANNI SUERGIU");
    	this.put("G288", "PALMI");
    	this.put("G289", "PALMIANO");
    	this.put("G290", "PALMOLI");
    	this.put("G291", "PALO DEL COLLE");
    	this.put("G292", "PALOMONTE");
    	this.put("G293", "PALOMBARA SABINA");
    	this.put("G294", "PALOMBARO");
    	this.put("G295", "PALOSCO");
    	this.put("G296", "PALU' DEL FERSINA");
    	this.put("G297", "PALU'");
    	this.put("G298", "PALUDI");
    	this.put("G299", "PLAUS .PLAUS.");
    	this.put("G300", "PALUZZA");
    	this.put("G302", "PAMPARATO");
    	this.put("G303", "PANCALIERI");
    	this.put("G304", "PANCARANA");
    	this.put("G305", "PANCHIA'");
    	this.put("G306", "PANDINO");
    	this.put("G307", "PANETTIERI");
    	this.put("G308", "PANICALE");
    	this.put("G309", "VILLARICCA");
    	this.put("G311", "PANNARANO");
    	this.put("G312", "PANNI");
    	this.put("G315", "PANTELLERIA");
    	this.put("G316", "PANTIGLIATE");
    	this.put("G317", "PAOLA");
    	this.put("G318", "PAOLISI");
    	this.put("G319", "VALDERICE");
    	this.put("G320", "PAPASIDERO");
    	this.put("G323", "PAPOZZE");
    	this.put("G324", "PARABIAGO");
    	this.put("G325", "PARABITA");
    	this.put("G327", "PARATICO");
    	this.put("G328", "PARCINES .PARTSCHINS.");
    	this.put("G329", "PARE'");
    	this.put("G330", "PARELLA");
    	this.put("G331", "PARENTI");
    	this.put("G333", "PARETE");
    	this.put("G334", "PARETO");
    	this.put("G335", "PARGHELIA");
    	this.put("G336", "PARLASCO");
    	this.put("G337", "PARMA");
    	this.put("G338", "PARODI LIGURE");
    	this.put("G339", "PAROLDO");
    	this.put("G340", "PAROLISE");
    	this.put("G342", "PARONA");
    	this.put("G344", "PARRANO");
    	this.put("G346", "PARRE");
    	this.put("G347", "PARTANNA");
    	this.put("G348", "PARTINICO");
    	this.put("G349", "PARUZZARO");
    	this.put("G350", "PARZANICA");
    	this.put("G352", "PASIAN DI PRATO");
    	this.put("G353", "PASIANO DI PORDENONE");
    	this.put("G354", "PASPARDO");
    	this.put("G358", "PASSERANO MARMORITO");
    	this.put("G359", "PASSIGNANO SUL TRASIMENO");
    	this.put("G361", "PASSIRANO");
    	this.put("G362", "PASTENA");
    	this.put("G364", "PASTORANO");
    	this.put("G365", "PASTRENGO");
    	this.put("G367", "PASTURANA");
    	this.put("G368", "PASTURO");
    	this.put("G370", "PATERNOPOLI");
    	this.put("G371", "PATERNO'");
    	this.put("G372", "PATERNO CALABRO");
    	this.put("G374", "PATRICA");
    	this.put("G376", "PATTADA");
    	this.put("G377", "PATTI");
    	this.put("G378", "PATU'");
    	this.put("G379", "PAU");
    	this.put("G381", "PAULARO");
    	this.put("G382", "PAULI ARBAREI");
    	this.put("G383", "SAN NICOLO' GERREI");
    	this.put("G384", "PAULILATINO");
    	this.put("G385", "PAULLO");
    	this.put("G386", "PAUPISI");
    	this.put("G387", "PAVAROLO");
    	this.put("G388", "PAVIA");
    	this.put("G389", "PAVIA DI UDINE");
    	this.put("G391", "PAVONE DEL MELLA");
    	this.put("G392", "PAVONE CANAVESE");
    	this.put("G393", "PAVULLO NEL FRIGNANO");
    	this.put("G394", "PAZZANO");
    	this.put("G395", "PECCIOLI");
    	this.put("G396", "PECCO");
    	this.put("G397", "PECETTO DI VALENZA");
    	this.put("G398", "PECETTO TORINESE");
    	this.put("G399", "PECORARA");
    	this.put("G400", "PEDACE");
    	this.put("G402", "PEDARA");
    	this.put("G403", "PEDASO");
    	this.put("G404", "PEDAVENA");
    	this.put("G406", "PEDEMONTE");
    	this.put("G407", "SAN PAOLO");
    	this.put("G408", "PEDEROBBA");
    	this.put("G410", "PEDESINA");
    	this.put("G411", "PEDIVIGLIANO");
    	this.put("G412", "PEDRENGO");
    	this.put("G415", "PEGLIO");
    	this.put("G416", "PEGLIO");
    	this.put("G417", "PEGOGNAGA");
    	this.put("G418", "PEIA");
    	this.put("G419", "PEIO");
    	this.put("G420", "PELAGO");
    	this.put("G421", "PELLA");
    	this.put("G424", "PELLEGRINO PARMENSE");
    	this.put("G426", "PELLEZZANO");
    	this.put("G427", "PELLIO INTELVI");
    	this.put("G428", "PELLIZZANO");
    	this.put("G429", "PELUGO");
    	this.put("G430", "PENANGO");
    	this.put("G431", "POGGIRIDENTI");
    	this.put("G432", "PENNA IN TEVERINA");
    	this.put("G433", "PENNABILLI");
    	this.put("G434", "PENNADOMO");
    	this.put("G435", "PENNAPIEDIMONTE");
    	this.put("G436", "PENNA SAN GIOVANNI");
    	this.put("G437", "PENNA SANT'ANDREA");
    	this.put("G438", "PENNE");
    	this.put("G439", "PENTONE");
    	this.put("G441", "PERANO");
    	this.put("G442", "PERAROLO DI CADORE");
    	this.put("G443", "PERCA .PERCHA.");
    	this.put("G444", "PERCILE");
    	this.put("G445", "PERDASDEFOGU");
    	this.put("G446", "PERDAXIUS");
    	this.put("G447", "PERDIFUMO");
    	this.put("G448", "PEREGO");
    	this.put("G449", "PERETO");
    	this.put("G450", "PERFUGAS");
    	this.put("G451", "PERGINE VALDARNO");
    	this.put("G452", "PERGINE VALSUGANA");
    	this.put("G453", "PERGOLA");
    	this.put("G454", "PERINALDO");
    	this.put("G455", "PERITO");
    	this.put("G456", "PERLEDO");
    	this.put("G457", "PERLETTO");
    	this.put("G458", "PERLO");
    	this.put("G459", "PERLOZ");
    	this.put("G461", "PERNUMIA");
    	this.put("G462", "PEROSA CANAVESE");
    	this.put("G463", "PEROSA ARGENTINA");
    	this.put("G465", "PERRERO");
    	this.put("G467", "SAN GIOVANNI IN PERSICETO");
    	this.put("G469", "PERSICO DOSIMO");
    	this.put("G471", "PERTENGO");
    	this.put("G474", "PERTICA ALTA");
    	this.put("G475", "PERTICA BASSA");
    	this.put("G476", "PERTOSA");
    	this.put("G477", "PERTUSIO");
    	this.put("G478", "PERUGIA");
    	this.put("G479", "PESARO");
    	this.put("G480", "PESCAGLIA");
    	this.put("G481", "PESCANTINA");
    	this.put("G482", "PESCARA");
    	this.put("G483", "PESCAROLO ED UNITI");
    	this.put("G484", "PESCASSEROLI");
    	this.put("G485", "PESCATE");
    	this.put("G486", "PESCHE");
    	this.put("G487", "PESCHICI");
    	this.put("G488", "PESCHIERA BORROMEO");
    	this.put("G489", "PESCHIERA DEL GARDA");
    	this.put("G491", "PESCIA");
    	this.put("G492", "PESCINA");
    	this.put("G493", "PESCOCOSTANZO");
    	this.put("G494", "PESCO SANNITA");
    	this.put("G495", "PESCOLANCIANO");
    	this.put("G496", "PESCOPAGANO");
    	this.put("G497", "PESCOPENNATARO");
    	this.put("G498", "PESCOROCCHIANO");
    	this.put("G499", "PESCOSANSONESCO");
    	this.put("G500", "PESCOSOLIDO");
    	this.put("G502", "PESSANO CON BORNAGO");
    	this.put("G504", "PESSINA CREMONESE");
    	this.put("G505", "PESSINETTO");
    	this.put("G506", "PETACCIATO");
    	this.put("G507", "TURANIA");
    	this.put("G508", "PETILIA POLICASTRO");
    	this.put("G509", "PETINA");
    	this.put("G510", "PETRALIA SOPRANA");
    	this.put("G511", "PETRALIA SOTTANA");
    	this.put("G512", "PETRELLA TIFERNINA");
    	this.put("G513", "PETRELLA SALTO");
    	this.put("G514", "PETRIANO");
    	this.put("G515", "PETRIOLO");
    	this.put("G516", "PETRITOLI");
    	this.put("G517", "PETRIZZI");
    	this.put("G518", "PETRONA'");
    	this.put("G519", "PETRURO IRPINO");
    	this.put("G520", "PETTENASCO");
    	this.put("G521", "PETTINENGO");
    	this.put("G522", "PETTINEO");
    	this.put("G523", "PETTORANELLO DEL MOLISE");
    	this.put("G524", "PETTORANO SUL GIZIO");
    	this.put("G525", "PETTORAZZA GRIMANI");
    	this.put("G526", "PEVERAGNO");
    	this.put("G528", "PEZZANA");
    	this.put("G529", "PEZZAZE");
    	this.put("G532", "PEZZOLO VALLE UZZONE");
    	this.put("G534", "PIACENZA D'ADIGE");
    	this.put("G535", "PIACENZA");
    	this.put("G536", "PIADENA");
    	this.put("G537", "PIAGGE");
    	this.put("G538", "PIAGGINE");
    	this.put("G540", "VALLE DELL'ANGELO");
    	this.put("G541", "PIANA DI MONTE VERNA");
    	this.put("G542", "PIANA CRIXIA");
    	this.put("G543", "PIANA DEGLI ALBANESI");
    	this.put("G545", "PONTBOSET");
    	this.put("G546", "PIAN CAMUNO");
    	this.put("G547", "PIANCASTAGNAIO");
    	this.put("G549", "PIANCOGNO");
    	this.put("G551", "PIANDIMELETO");
    	this.put("G552", "PIAN DI SCO");
    	this.put("G553", "PIANE CRATI");
    	this.put("G555", "PIANELLA");
    	this.put("G556", "PIANELLO DEL LARIO");
    	this.put("G557", "PIANELLO VAL TIDONE");
    	this.put("G558", "PIANENGO");
    	this.put("G559", "PIANEZZA");
    	this.put("G560", "PIANEZZE");
    	this.put("G561", "PIANFEI");
    	this.put("G564", "PIANICO");
    	this.put("G565", "PIANIGA");
    	this.put("G566", "SAN BENEDETTO VAL DI SAMBRO");
    	this.put("G568", "PIANO DI SORRENTO");
    	this.put("G570", "PIANORO");
    	this.put("G571", "PIANSANO");
    	this.put("G572", "PIANTEDO");
    	this.put("G574", "PIARIO");
    	this.put("G575", "PIASCO");
    	this.put("G576", "PIATEDA");
    	this.put("G577", "PIATTO");
    	this.put("G579", "PIAZZA BREMBANA");
    	this.put("G580", "PIAZZA ARMERINA");
    	this.put("G582", "PIAZZA AL SERCHIO");
    	this.put("G583", "PIAZZATORRE");
    	this.put("G587", "PIAZZOLA SUL BRENTA");
    	this.put("G588", "PIAZZOLO");
    	this.put("G589", "PICCIANO");
    	this.put("G590", "PICERNO");
    	this.put("G591", "PICINISCO");
    	this.put("G592", "PICO");
    	this.put("G593", "PIEA");
    	this.put("G594", "PIEDICAVALLO");
    	this.put("G596", "PIEDIMONTE MATESE");
    	this.put("G597", "PIEDIMONTE ETNEO");
    	this.put("G598", "PIEDIMONTE SAN GERMANO");
    	this.put("G600", "PIEDIMULERA");
    	this.put("G601", "PIEGARO");
    	this.put("G602", "PIENZA");
    	this.put("G603", "PIERANICA");
    	this.put("G604", "PIETRAMONTECORVINO");
    	this.put("G605", "PIETRA LIGURE");
    	this.put("G606", "PIETRABBONDANTE");
    	this.put("G607", "PIETRABRUNA");
    	this.put("G608", "PIETRACAMELA");
    	this.put("G609", "PIETRACATELLA");
    	this.put("G610", "PIETRACUPA");
    	this.put("G611", "PIETRADEFUSI");
    	this.put("G612", "PIETRA DE' GIORGI");
    	this.put("G613", "PIETRAFERRAZZANA");
    	this.put("G614", "SATRIANO DI LUCANIA");
    	this.put("G615", "PIETRAFITTA");
    	this.put("G616", "PIETRAGALLA");
    	this.put("G618", "PIETRALUNGA");
    	this.put("G619", "PIETRA MARAZZI");
    	this.put("G620", "PIETRAMELARA");
    	this.put("G621", "PIETRANICO");
    	this.put("G622", "PIETRAPAOLA");
    	this.put("G623", "PIETRAPERTOSA");
    	this.put("G624", "PIETRAPERZIA");
    	this.put("G625", "PIETRAPORZIO");
    	this.put("G626", "PIETRAROJA");
    	this.put("G627", "PIETRARUBBIA");
    	this.put("G628", "PIETRASANTA");
    	this.put("G629", "PIETRASTORNINA");
    	this.put("G630", "PIETRAVAIRANO");
    	this.put("G631", "PIETRELCINA");
    	this.put("G632", "PIEVE DI TECO");
    	this.put("G633", "PIEVE DI CORIANO");
    	this.put("G634", "PIEVE EMANUELE");
    	this.put("G635", "PIEVE ALBIGNOLA");
    	this.put("G636", "PIEVE A NIEVOLE");
    	this.put("G637", "PIEVEBOVIGLIANA");
    	this.put("G638", "PIEVE D'ALPAGO");
    	this.put("G639", "PIEVE DEL CAIRO");
    	this.put("G641", "PIEVE DI BONO");
    	this.put("G642", "PIEVE DI CADORE");
    	this.put("G643", "PIEVE DI CENTO");
    	this.put("G644", "PIEVE DI LEDRO");
    	this.put("G645", "PIEVE DI SOLIGO");
    	this.put("G646", "PIEVE LIGURE");
    	this.put("G647", "PIEVE D'OLMI");
    	this.put("G648", "PIEVE FOSCIANA");
    	this.put("G649", "PIEVEPELAGO");
    	this.put("G650", "PIEVE PORTO MORONE");
    	this.put("G651", "PIEVE SAN GIACOMO");
    	this.put("G653", "PIEVE SANTO STEFANO");
    	this.put("G654", "RAMISETO");
    	this.put("G656", "PIEVE TESINO");
    	this.put("G657", "PIEVE TORINA");
    	this.put("G658", "PIEVE VERGONTE");
    	this.put("G659", "PIGLIO");
    	this.put("G660", "PIGNA");
    	this.put("G661", "PIGNATARO MAGGIORE");
    	this.put("G662", "PIGNATARO INTERAMNA");
    	this.put("G663", "PIGNOLA");
    	this.put("G664", "PIGNONE");
    	this.put("G665", "PIGRA");
    	this.put("G666", "PILA");
    	this.put("G669", "PIMENTEL");
    	this.put("G670", "PIMONTE");
    	this.put("G671", "PINAROLO PO");
    	this.put("G672", "PINASCA");
    	this.put("G673", "PINCARA");
    	this.put("G674", "PINEROLO");
    	this.put("G676", "PINO D'ASTI");
    	this.put("G677", "PINO SULLA SPONDA DEL LAGO MAGGIORE");
    	this.put("G678", "PINO TORINESE");
    	this.put("G680", "PINZANO AL TAGLIAMENTO");
    	this.put("G681", "PINZOLO");
    	this.put("G682", "PIOBBICO");
    	this.put("G683", "PIOBESI D'ALBA");
    	this.put("G684", "PIOBESI TORINESE");
    	this.put("G685", "PIODE");
    	this.put("G686", "PIOLTELLO");
    	this.put("G687", "PIOMBINO");
    	this.put("G688", "PIOMBINO DESE");
    	this.put("G690", "PIORACO");
    	this.put("G691", "PIOSSASCO");
    	this.put("G692", "PIOVA' MASSAIA");
    	this.put("G693", "PIOVE DI SACCO");
    	this.put("G694", "PIOVENE ROCCHETTE");
    	this.put("G695", "PIOVERA");
    	this.put("G696", "PIOZZANO");
    	this.put("G697", "PIOZZO");
    	this.put("G698", "PRIVERNO");
    	this.put("G699", "PIRAINO");
    	this.put("G702", "PISA");
    	this.put("G703", "PISANO");
    	this.put("G704", "PISONIANO");
    	this.put("G705", "PISCINA");
    	this.put("G707", "PISCIOTTA");
    	this.put("G710", "PISOGNE");
    	this.put("G712", "PISTICCI");
    	this.put("G713", "PISTOIA");
    	this.put("G715", "PITEGLIO");
    	this.put("G716", "PITIGLIANO");
    	this.put("G717", "PIUBEGA");
    	this.put("G718", "PIURO");
    	this.put("G719", "PIVERONE");
    	this.put("G720", "PIZZALE");
    	this.put("G721", "PIZZIGHETTONE");
    	this.put("G722", "PIZZO");
    	this.put("G724", "PIZZOFERRATO");
    	this.put("G726", "PIZZOLI");
    	this.put("G727", "PIZZONE");
    	this.put("G728", "PIZZONI");
    	this.put("G729", "PLACANICA");
    	this.put("G733", "PLATACI");
    	this.put("G734", "PLATANIA");
    	this.put("G735", "PLATI'");
    	this.put("G736", "TAIPANA");
    	this.put("G737", "PLESIO");
    	this.put("G740", "PLOAGHE");
    	this.put("G741", "PLODIO");
    	this.put("G742", "POCAPAGLIA");
    	this.put("G743", "POCENIA");
    	this.put("G746", "PODENZANA");
    	this.put("G747", "PODENZANO");
    	this.put("G749", "POFI");
    	this.put("G751", "POGGIARDO");
    	this.put("G752", "POGGIBONSI");
    	this.put("G753", "POGGIO RUSCO");
    	this.put("G754", "POGGIO A CAIANO");
    	this.put("G755", "POGGIO BERNI");
    	this.put("G756", "POGGIO BUSTONE");
    	this.put("G757", "POGGIO CATINO");
    	this.put("G758", "POGGIODOMO");
    	this.put("G760", "POGGIOFIORITO");
    	this.put("G761", "POGGIO IMPERIALE");
    	this.put("G762", "POGGIOMARINO");
    	this.put("G763", "POGGIO MIRTETO");
    	this.put("G764", "POGGIO MOIANO");
    	this.put("G765", "POGGIO NATIVO");
    	this.put("G766", "POGGIO PICENZE");
    	this.put("G767", "POGGIOREALE");
    	this.put("G768", "POGGIO RENATICO");
    	this.put("G769", "POGGIORSINI");
    	this.put("G770", "POGGIO SAN LORENZO");
    	this.put("G771", "POGGIO SAN MARCELLO");
    	this.put("G772", "POGLIANO MILANESE");
    	this.put("G773", "POGNANA LARIO");
    	this.put("G774", "POGNANO");
    	this.put("G775", "POGNO");
    	this.put("G776", "POJANA MAGGIORE");
    	this.put("G777", "POIRINO");
    	this.put("G779", "POLAVENO");
    	this.put("G780", "POLCENIGO");
    	this.put("G782", "POLESELLA");
    	this.put("G783", "POLESINE PARMENSE");
    	this.put("G784", "POLI");
    	this.put("G785", "POLIA");
    	this.put("G786", "POLICORO");
    	this.put("G787", "POLIGNANO A MARE");
    	this.put("G788", "SAN PIETRO IN CERRO");
    	this.put("G789", "POLINAGO");
    	this.put("G790", "POLINO");
    	this.put("G791", "POLISTENA");
    	this.put("G792", "POLIZZI GENEROSA");
    	this.put("G793", "POLLA");
    	this.put("G794", "POLLEIN");
    	this.put("G795", "POLLENA TROCCHIA");
    	this.put("G796", "POLLICA");
    	this.put("G797", "POLLINA");
    	this.put("G798", "POLLONE");
    	this.put("G799", "POLLUTRI");
    	this.put("G800", "POLONGHERA");
    	this.put("G801", "POLPENAZZE DEL GARDA");
    	this.put("G802", "POLVERARA");
    	this.put("G803", "POLVERIGI");
    	this.put("G804", "POMARANCE");
    	this.put("G805", "POMARETTO");
    	this.put("G806", "POMARICO");
    	this.put("G807", "POMARO MONFERRATO");
    	this.put("G808", "POMAROLO");
    	this.put("G809", "POMBIA");
    	this.put("G811", "POMEZIA");
    	this.put("G812", "POMIGLIANO D'ARCO");
    	this.put("G813", "POMPEI");
    	this.put("G814", "POMPEIANA");
    	this.put("G815", "POMPIANO");
    	this.put("G816", "POMPONESCO");
    	this.put("G817", "POMPU");
    	this.put("G818", "PONCARALE");
    	this.put("G820", "PONDERANO");
    	this.put("G821", "PONNA");
    	this.put("G822", "PONSACCO");
    	this.put("G823", "PONSO");
    	this.put("G825", "PONTASSIEVE");
    	this.put("G826", "PONT CANAVESE");
    	this.put("G827", "PONTE");
    	this.put("G829", "PONTE IN VALTELLINA");
    	this.put("G830", "PONTE GARDENA .WAIDBRUCK.");
    	this.put("G831", "PONTEBBA");
    	this.put("G833", "PONTE BUGGIANESE");
    	this.put("G834", "PONTECAGNANO FAIANO");
    	this.put("G836", "PONTECCHIO POLESINE");
    	this.put("G837", "PONTECHIANALE");
    	this.put("G838", "PONTECORVO");
    	this.put("G839", "PONTECURONE");
    	this.put("G840", "PONTEDASSIO");
    	this.put("G842", "PONTE DELL'OLIO");
    	this.put("G843", "PONTEDERA");
    	this.put("G844", "PONTE DI LEGNO");
    	this.put("G846", "PONTE DI PIAVE");
    	this.put("G847", "PONTE LAMBRO");
    	this.put("G848", "PONTELANDOLFO");
    	this.put("G849", "PONTELATONE");
    	this.put("G850", "PONTELONGO");
    	this.put("G851", "PONTE NIZZA");
    	this.put("G852", "PONTENURE");
    	this.put("G853", "PONTERANICA");
    	this.put("G854", "PONT-SAINT-MARTIN");
    	this.put("G855", "PONTE SAN NICOLO'");
    	this.put("G856", "PONTE SAN PIETRO");
    	this.put("G858", "PONTESTURA");
    	this.put("G859", "PONTEVICO");
    	this.put("G860", "PONTEY");
    	this.put("G861", "PONTI");
    	this.put("G862", "PONTI SUL MINCIO");
    	this.put("G864", "PONTIDA");
    	this.put("G865", "PONTINIA");
    	this.put("G866", "PONTINVREA");
    	this.put("G867", "PONTIROLO NUOVO");
    	this.put("G869", "PONTOGLIO");
    	this.put("G870", "PONTREMOLI");
    	this.put("G871", "PONZA");
    	this.put("G872", "PONZANO MONFERRATO");
    	this.put("G873", "PONZANO DI FERMO");
    	this.put("G874", "PONZANO ROMANO");
    	this.put("G875", "PONZANO VENETO");
    	this.put("G877", "PONZONE");
    	this.put("G878", "POPOLI");
    	this.put("G879", "POPPI");
    	this.put("G881", "PORANO");
    	this.put("G882", "PORCARI");
    	this.put("G886", "PORCIA");
    	this.put("G887", "STELLA CILENTO");
    	this.put("G888", "PORDENONE");
    	this.put("G889", "PORLEZZA");
    	this.put("G890", "PORNASSIO");
    	this.put("G891", "PORPETTO");
    	this.put("G894", "PORTACOMARO");
    	this.put("G895", "PORTALBERA");
    	this.put("G900", "PORTE");
    	this.put("G902", "PORTICI");
    	this.put("G903", "PORTICO DI CASERTA");
    	this.put("G904", "PORTICO E SAN BENEDETTO");
    	this.put("G905", "PORTIGLIOLA");
    	this.put("G906", "PORTO CERESIO");
    	this.put("G907", "PORTO VALTRAVAGLIA");
    	this.put("G909", "PORTOBUFFOLE'");
    	this.put("G910", "PORTOCANNONE");
    	this.put("G912", "PORTOFERRAIO");
    	this.put("G913", "PORTOFINO");
    	this.put("G914", "PORTOGRUARO");
    	this.put("G916", "PORTOMAGGIORE");
    	this.put("G917", "PORTO MANTOVANO");
    	this.put("G919", "PORTO RECANATI");
    	this.put("G920", "PORTO SAN GIORGIO");
    	this.put("G921", "PORTO SANT'ELPIDIO");
    	this.put("G922", "PORTOSCUSO");
    	this.put("G923", "PORTO TOLLE");
    	this.put("G924", "PORTO TORRES");
    	this.put("G925", "PORTOVENERE");
    	this.put("G926", "PORTO VIRO");
    	this.put("G927", "PORTULA");
    	this.put("G929", "POSADA");
    	this.put("G931", "POSINA");
    	this.put("G932", "POSITANO");
    	this.put("G933", "POSSAGNO");
    	this.put("G934", "POSTA");
    	this.put("G935", "POSTA FIBRENO");
    	this.put("G936", "POSTAL .BURGSTALL.");
    	this.put("G937", "POSTALESIO");
    	this.put("G939", "POSTIGLIONE");
    	this.put("G940", "POSTUA");
    	this.put("G942", "POTENZA");
    	this.put("G943", "POVE DEL GRAPPA");
    	this.put("G944", "POVEGLIANO");
    	this.put("G945", "POVEGLIANO VERONESE");
    	this.put("G947", "POVIGLIO");
    	this.put("G949", "POVOLETTO");
    	this.put("G950", "POZZA DI FASSA");
    	this.put("G951", "POZZAGLIA SABINA");
    	this.put("G953", "POZZALLO");
    	this.put("G954", "POZZILLI");
    	this.put("G955", "POZZO D'ADDA");
    	this.put("G957", "POZZOLEONE");
    	this.put("G959", "POZZOLENGO");
    	this.put("G960", "POZZOL GROPPO");
    	this.put("G961", "POZZOLO FORMIGARO");
    	this.put("G962", "POZZOMAGGIORE");
    	this.put("G963", "POZZONOVO");
    	this.put("G964", "POZZUOLI");
    	this.put("G965", "POZZUOLO MARTESANA");
    	this.put("G966", "POZZUOLO DEL FRIULI");
    	this.put("G968", "PRADALUNGA");
    	this.put("G969", "PRADAMANO");
    	this.put("G970", "PRADLEVES");
    	this.put("G972", "SASSO MARCONI");
    	this.put("G973", "PRAGELATO");
    	this.put("G974", "PRAY");
    	this.put("G975", "PRAIA A MARE");
    	this.put("G976", "PRAIANO");
    	this.put("G977", "PRALBOINO");
    	this.put("G978", "PRALI");
    	this.put("G979", "PRALORMO");
    	this.put("G980", "PRALUNGO");
    	this.put("G981", "PRAMAGGIORE");
    	this.put("G982", "PRAMOLLO");
    	this.put("G985", "PRAROLO");
    	this.put("G986", "PRAROSTINO");
    	this.put("G987", "PRASCO");
    	this.put("G988", "PRASCORSANO");
    	this.put("G989", "PRASO");
    	this.put("G990", "PRATA DI PRINCIPATO ULTRA");
    	this.put("G991", "PRATA SANNITA");
    	this.put("G992", "PRATA D'ANSIDONIA");
    	this.put("G993", "PRATA CAMPORTACCIO");
    	this.put("G994", "PRATA DI PORDENONE");
    	this.put("G995", "PRATELLA");
    	this.put("G997", "PRATIGLIONE");
    	this.put("G999", "PRATO");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
