package cities_codes;

import java.util.HashMap;

@SuppressWarnings("serial")
public class CitiesCodes_I extends HashMap<String, String> {

    public CitiesCodes_I(){
    	this.put("I002", "SAN MARTINO SANNITA");
    	this.put("I003", "SAN MARTINO BUON ALBERGO");
    	this.put("I005", "SAN MARTINO DALL'ARGINE");
    	this.put("I007", "SAN MARTINO DEL LAGO");
    	this.put("I008", "SAN MARTINO DI LUPARI");
    	this.put("I011", "SAN MARTINO IN RIO");
    	this.put("I012", "SAN MARTINO IN STRADA");
    	this.put("I014", "SAN MARTINO SICCOMARIO");
    	this.put("I016", "SAN MARTINO VALLE CAUDINA");
    	this.put("I017", "SAN MARZANO OLIVETO");
    	this.put("I018", "SAN MARZANO DI SAN GIUSEPPE");
    	this.put("I019", "SAN MARZANO SUL SARNO");
    	this.put("I023", "SAN MASSIMO");
    	this.put("I024", "SAN MAURIZIO CANAVESE");
    	this.put("I025", "SAN MAURIZIO D'OPAGLIO");
    	this.put("I026", "SAN MAURO MARCHESATO");
    	this.put("I027", "SAN MAURO PASCOLI");
    	this.put("I028", "SAN MAURO CASTELVERDE");
    	this.put("I029", "SAN MAURO FORTE");
    	this.put("I030", "SAN MAURO TORINESE");
    	this.put("I031", "SAN MAURO CILENTO");
    	this.put("I032", "SAN MAURO LA BRUCA");
    	this.put("I034", "SAN MICHELE DI SERINO");
    	this.put("I035", "SAN MICHELE DI GANZARIA");
    	this.put("I037", "SAN MICHELE MONDOVI'");
    	this.put("I040", "SAN MICHELE AL TAGLIAMENTO");
    	this.put("I042", "SAN MICHELE ALL'ADIGE");
    	this.put("I045", "SAN MICHELE SALENTINO");
    	this.put("I046", "SAN MINIATO");
    	this.put("I047", "SAN NAZARIO");
    	this.put("I048", "SANNAZZARO DE' BURGONDI");
    	this.put("I049", "SAN NAZZARO");
    	this.put("I051", "SAN NAZZARO VAL CAVARGNA");
    	this.put("I052", "SAN NAZZARO SESIA");
    	this.put("I053", "SANNICANDRO DI BARI");
    	this.put("I054", "SAN NICANDRO GARGANICO");
    	this.put("I056", "SAN NICOLA LA STRADA");
    	this.put("I057", "SAN NICOLA DELL'ALTO");
    	this.put("I058", "SAN NICOLA DA CRISSA");
    	this.put("I059", "SANNICOLA");
    	this.put("I060", "SAN NICOLA ARCELLA");
    	this.put("I061", "SAN NICOLA BARONIA");
    	this.put("I062", "SAN NICOLA MANFREDI");
    	this.put("I063", "SAN NICOLO' DI COMELICO");
    	this.put("I065", "SAN PANCRAZIO .ST PANKRAZ.");
    	this.put("I066", "SAN PANCRAZIO SALENTINO");
    	this.put("I071", "SAN PAOLO DI JESI");
    	this.put("I072", "SAN PAOLO DI CIVITATE");
    	this.put("I073", "SAN PAOLO BEL SITO");
    	this.put("I074", "SAN PAOLO CERVO");
    	this.put("I076", "SAN PAOLO SOLBRITO");
    	this.put("I079", "SAN PELLEGRINO TERME");
    	this.put("I082", "SAN PIER D'ISONZO");
    	this.put("I084", "SAN PIER NICETO");
    	this.put("I085", "SAN PIERO A SIEVE");
    	this.put("I086", "SAN PIERO PATTI");
    	this.put("I088", "SAN PIETRO DI CADORE");
    	this.put("I089", "SAN PIETRO AL TANAGRO");
    	this.put("I090", "SAN PIETRO VAL LEMINA");
    	this.put("I092", "SAN PIETRO AL NATISONE");
    	this.put("I093", "SAN PIETRO A MAIDA");
    	this.put("I095", "SAN PIETRO APOSTOLO");
    	this.put("I096", "SAN PIETRO AVELLANA");
    	this.put("I098", "SAN PIETRO CLARENZA");
    	this.put("I102", "SAN PIETRO DI CARIDA'");
    	this.put("I103", "SAN PIETRO DI FELETTO");
    	this.put("I105", "SAN PIETRO DI MORUBIO");
    	this.put("I107", "SAN PIETRO IN GU");
    	this.put("I108", "SAN PIETRO IN AMANTEA");
    	this.put("I109", "SAN PIETRO IN CARIANO");
    	this.put("I110", "SAN PIETRO IN CASALE");
    	this.put("I113", "SAN PIETRO INFINE");
    	this.put("I114", "SAN PIETRO IN GUARANO");
    	this.put("I115", "SAN PIETRO IN LAMA");
    	this.put("I116", "SAN PIETRO MOSEZZO");
    	this.put("I117", "SAN PIETRO MUSSOLINO");
    	this.put("I118", "VILLA SAN PIETRO");
    	this.put("I119", "SAN PIETRO VERNOTICO");
    	this.put("I120", "SAN PIETRO VIMINARIO");
    	this.put("I121", "SAN PIO DELLE CAMERE");
    	this.put("I122", "SAN POLO MATESE");
    	this.put("I123", "SAN POLO D'ENZA");
    	this.put("I124", "SAN POLO DI PIAVE");
    	this.put("I125", "SAN POLO DEI CAVALIERI");
    	this.put("I126", "SAN PONSO");
    	this.put("I128", "SAN POSSIDONIO");
    	this.put("I129", "SAN POTITO ULTRA");
    	this.put("I130", "SAN POTITO SANNITICO");
    	this.put("I131", "SAN PRISCO");
    	this.put("I132", "SAN PROCOPIO");
    	this.put("I133", "SAN PROSPERO");
    	this.put("I135", "SAN QUIRICO D'ORCIA");
    	this.put("I136", "SAN QUIRINO");
    	this.put("I137", "SAN RAFFAELE CIMENA");
    	this.put("I138", "SANREMO");
    	this.put("I139", "SAN ROBERTO");
    	this.put("I140", "SAN ROCCO AL PORTO");
    	this.put("I142", "SAN ROMANO IN GARFAGNANA");
    	this.put("I143", "SAN RUFO");
    	this.put("I144", "SAN SALVATORE MONFERRATO");
    	this.put("I145", "SAN SALVATORE TELESINO");
    	this.put("I147", "SAN SALVATORE DI FITALIA");
    	this.put("I148", "SAN SALVO");
    	this.put("I150", "SAN SEBASTIANO CURONE");
    	this.put("I151", "SAN SEBASTIANO AL VESUVIO");
    	this.put("I152", "SAN SEBASTIANO DA PO");
    	this.put("I153", "SAN SECONDO PARMENSE");
    	this.put("I154", "SAN SECONDO DI PINEROLO");
    	this.put("I155", "SANSEPOLCRO");
    	this.put("I156", "SAN SEVERINO MARCHE");
    	this.put("I157", "SAN SEVERINO LUCANO");
    	this.put("I158", "SAN SEVERO");
    	this.put("I162", "SAN SIRO");
    	this.put("I163", "SAN SOSSIO BARONIA");
    	this.put("I164", "SAN SOSTENE");
    	this.put("I165", "SAN SOSTI");
    	this.put("I166", "SAN SPERATE");
    	this.put("I168", "SANTA BRIGIDA");
    	this.put("I169", "SANTA CATERINA VILLARMOSA");
    	this.put("I170", "SANTA CATERINA DELLO IONIO");
    	this.put("I171", "SANTA CATERINA ALBANESE");
    	this.put("I172", "SANTA CESAREA TERME");
    	this.put("I173", "SANTA CRISTINA VALGARDENA .ST CHRISTINA IN G.");
    	this.put("I174", "SANTA CRISTINA GELA");
    	this.put("I175", "SANTA CRISTINA E BISSONE");
    	this.put("I176", "SANTA CRISTINA D'ASPROMONTE");
    	this.put("I177", "SANTA CROCE SULL'ARNO");
    	this.put("I178", "SANTA CROCE CAMERINA");
    	this.put("I179", "SANTA CROCE DEL SANNIO");
    	this.put("I181", "SANTA CROCE DI MAGLIANO");
    	this.put("I182", "SANTADI");
    	this.put("I183", "SANTA DOMENICA TALAO");
    	this.put("I184", "SANTA DOMENICA VITTORIA");
    	this.put("I185", "SANTA ELISABETTA");
    	this.put("I187", "SANTA FIORA");
    	this.put("I188", "SANTA FLAVIA");
    	this.put("I189", "SANT'AGAPITO");
    	this.put("I190", "SANT'AGATA FOSSILI");
    	this.put("I191", "SANT'AGATA BOLOGNESE");
    	this.put("I192", "SANT'AGATA DI ESARO");
    	this.put("I193", "SANT'AGATA DI PUGLIA");
    	this.put("I196", "SANT'AGATA SUL SANTERNO");
    	this.put("I197", "SANT'AGATA DE' GOTI");
    	this.put("I198", "SANT'AGATA DEL BIANCO");
    	this.put("I199", "SANT'AGATA DI MILITELLO");
    	this.put("I201", "SANT'AGATA FELTRIA");
    	this.put("I202", "SANT'AGATA LI BATTIATI");
    	this.put("I203", "SANTA GIULETTA");
    	this.put("I205", "SANTA GIUSTA");
    	this.put("I206", "SANTA GIUSTINA");
    	this.put("I207", "SANTA GIUSTINA IN COLLE");
    	this.put("I208", "SANT'AGNELLO");
    	this.put("I209", "SANT'AGOSTINO");
    	this.put("I210", "SANT'ALBANO STURA");
    	this.put("I213", "SANT'ALESSIO CON VIALONE");
    	this.put("I214", "SANT'ALESSIO IN ASPROMONTE");
    	this.put("I215", "SANT'ALESSIO SICULO");
    	this.put("I216", "SANT'ALFIO");
    	this.put("I217", "SANTA LUCE");
    	this.put("I219", "SANTA LUCIA DI SERINO");
    	this.put("I220", "SANTA LUCIA DEL MELA");
    	this.put("I221", "SANTA LUCIA DI PIAVE");
    	this.put("I224", "SANTA MARGHERITA DI BELICE");
    	this.put("I225", "SANTA MARGHERITA LIGURE");
    	this.put("I226", "SANTA MARGHERITA D'ADIGE");
    	this.put("I230", "SANTA MARGHERITA DI STAFFORA");
    	this.put("I232", "SANTA MARIA A MONTE");
    	this.put("I233", "SANTA MARIA A VICO");
    	this.put("I234", "SANTA MARIA CAPUA VETERE");
    	this.put("I236", "TRAVACO' SICCOMARIO");
    	this.put("I237", "SANTA MARIA DELLA VERSA");
    	this.put("I238", "SANTA MARIA DEL MOLISE");
    	this.put("I240", "SANTA MARIA DI LICODIA");
    	this.put("I242", "SANTA MARIA DI SALA");
    	this.put("I243", "SANTA MARIA HOE'");
    	this.put("I244", "SANTA MARIA IMBARO");
    	this.put("I247", "SANTA MARIA LA FOSSA");
    	this.put("I248", "SANTA MARIA LA LONGA");
    	this.put("I249", "SANTA MARIA MAGGIORE");
    	this.put("I251", "SANTA MARIA NUOVA");
    	this.put("I253", "SANTA MARINA");
    	this.put("I254", "SANTA MARINA SALINA");
    	this.put("I255", "SANTA MARINELLA");
    	this.put("I256", "SANT'AMBROGIO SUL GARIGLIANO");
    	this.put("I258", "SANT'AMBROGIO DI TORINO");
    	this.put("I259", "SANT'AMBROGIO DI VALPOLICELLA");
    	this.put("I260", "SANTOMENNA");
    	this.put("I261", "SAN TAMMARO");
    	this.put("I262", "SANT'ANASTASIA");
    	this.put("I263", "SANT'ANATOLIA DI NARCO");
    	this.put("I264", "SANT'ANDREA DI CONZA");
    	this.put("I265", "SANT'ANDREA DEL GARIGLIANO");
    	this.put("I266", "SANT'ANDREA APOSTOLO DELLO IONIO");
    	this.put("I271", "SANT'ANDREA FRIUS");
    	this.put("I273", "SANT'ANGELO D'ALIFE");
    	this.put("I274", "SANT'ANGELO LODIGIANO");
    	this.put("I275", "SANT'ANGELO DI PIOVE DI SACCO");
    	this.put("I276", "SANT'ANGELO LOMELLINA");
    	this.put("I277", "SANT'ANGELO A CUPOLO");
    	this.put("I278", "SANT'ANGELO A FASANELLA");
    	this.put("I279", "SANT'ANGELO ALL'ESCA");
    	this.put("I280", "SANT'ANGELO A SCALA");
    	this.put("I281", "SANT'ANGELO DEI LOMBARDI");
    	this.put("I282", "SANT'ANGELO DEL PESCO");
    	this.put("I283", "SANT'ANGELO DI BROLO");
    	this.put("I284", "SANT'ANGELO ROMANO");
    	this.put("I285", "SANT'ANGELO IN LIZZOLA");
    	this.put("I286", "SANT'ANGELO IN PONTANO");
    	this.put("I287", "SANT'ANGELO IN VADO");
    	this.put("I288", "SANT'ANGELO LE FRATTE");
    	this.put("I289", "SANT'ANGELO LIMOSANO");
    	this.put("I290", "SANT'ANGELO MUXARO");
    	this.put("I291", "SANTA NINFA");
    	this.put("I292", "SANT'ANNA D'ALFAEDO");
    	this.put("I293", "SANT'ANTIMO");
    	this.put("I294", "SANT'ANTIOCO");
    	this.put("I296", "SANT'ANTONINO DI SUSA");
    	this.put("I298", "VILLA SANT'ANTONIO");
    	this.put("I300", "SANT'ANTONIO ABATE");
    	this.put("I301", "SANTA PAOLINA");
    	this.put("I302", "SANT'APOLLINARE");
    	this.put("I304", "SANTARCANGELO DI ROMAGNA");
    	this.put("I305", "SANT'ARCANGELO");
    	this.put("I306", "SANT'ARPINO");
    	this.put("I307", "SANT'ARSENIO");
    	this.put("I308", "SANTA SEVERINA");
    	this.put("I309", "SANTA SOFIA D'EPIRO");
    	this.put("I310", "SANTA SOFIA");
    	this.put("I311", "SANTA TERESA DI RIVA");
    	this.put("I312", "SANTA TERESA GALLURA");
    	this.put("I314", "SANTA VENERINA");
    	this.put("I315", "SANTA VITTORIA IN MATENANO");
    	this.put("I316", "SANTA VITTORIA D'ALBA");
    	this.put("I317", "SANT'EGIDIO DEL MONTE ALBINO");
    	this.put("I318", "SANT'EGIDIO ALLA VIBRATA");
    	this.put("I319", "SANT'ELENA");
    	this.put("I320", "SANT'ELIA A PIANISI");
    	this.put("I321", "SANT'ELIA FIUMERAPIDO");
    	this.put("I322", "VALLEFIORITA");
    	this.put("I324", "SANT'ELPIDIO A MARE");
    	this.put("I326", "SANTE MARIE");
    	this.put("I327", "SANTENA");
    	this.put("I328", "SAN TEODORO");
    	this.put("I329", "SAN TEODORO");
    	this.put("I330", "SANTERAMO IN COLLE");
    	this.put("I332", "SANT'EUFEMIA A MAIELLA");
    	this.put("I333", "SANT'EUFEMIA D'ASPROMONTE");
    	this.put("I335", "SANT'EUSANIO DEL SANGRO");
    	this.put("I336", "SANT'EUSANIO FORCONESE");
    	this.put("I337", "SANTHIA'");
    	this.put("I339", "SANTI COSMA E DAMIANO");
    	this.put("I341", "SANT'ILARIO DELLO IONIO");
    	this.put("I342", "SANT'ILARIO D'ENZA");
    	this.put("I344", "SANT'IPPOLITO");
    	this.put("I345", "ZOLDO ALTO");
    	this.put("I346", "SANT'OLCESE");
    	this.put("I347", "SAN TOMASO AGORDINO");
    	this.put("I348", "SANT'OMERO");
    	this.put("I349", "SANT'OMOBONO TERME");
    	this.put("I350", "SANT'ONOFRIO");
    	this.put("I351", "SANTOPADRE");
    	this.put("I352", "SANT'ORESTE");
    	this.put("I353", "SANTORSO");
    	this.put("I354", "SANT'ORSOLA TERME");
    	this.put("I356", "SANTO STEFANO QUISQUINA");
    	this.put("I357", "SANTO STEFANO DEL SOLE");
    	this.put("I359", "SANTO STEFANO DI ROGLIANO");
    	this.put("I360", "SANTO STEFANO DI SESSANIO");
    	this.put("I361", "SANTO STEFANO TICINO");
    	this.put("I362", "SANTO STEFANO LODIGIANO");
    	this.put("I363", "SANTO STEFANO DI MAGRA");
    	this.put("I364", "VILLA SANTO STEFANO");
    	this.put("I365", "SANTO STEFANO AL MARE");
    	this.put("I367", "SANTO STEFANO BELBO");
    	this.put("I368", "SANTO STEFANO D'AVETO");
    	this.put("I370", "SANTO STEFANO DI CAMASTRA");
    	this.put("I371", "SANTO STEFANO IN ASPROMONTE");
    	this.put("I372", "SANTO STEFANO ROERO");
    	this.put("I373", "SAN STINO DI LIVENZA");
    	this.put("I374", "SANTU LUSSURGIU");
    	this.put("I375", "SANT'URBANO");
    	this.put("I376", "SAN VALENTINO IN ABRUZZO CITERIORE");
    	this.put("I377", "SAN VALENTINO TORIO");
    	this.put("I381", "SAN VENANZO");
    	this.put("I382", "SAN VENDEMIANO");
    	this.put("I384", "SAN VERO MILIS");
    	this.put("I388", "SAN VINCENZO LA COSTA");
    	this.put("I389", "SAN VINCENZO VALLE ROVETO");
    	this.put("I390", "SAN VINCENZO");
    	this.put("I391", "SAN VITALIANO");
    	this.put("I392", "SAN VITO DI CADORE");
    	this.put("I393", "SAN VITO SULLO IONIO");
    	this.put("I394", "SAN VITO CHIETINO");
    	this.put("I396", "SAN VITO DEI NORMANNI");
    	this.put("I400", "SAN VITO ROMANO");
    	this.put("I401", "SAN VITO DI LEGUZZANO");
    	this.put("I402", "SAN VITO");
    	this.put("I403", "SAN VITO AL TAGLIAMENTO");
    	this.put("I404", "SAN VITO AL TORRE");
    	this.put("I405", "SAN VITO DI FAGAGNA");
    	this.put("I407", "SAN VITO LO CAPO");
    	this.put("I408", "SAN VITTORE DEL LAZIO");
    	this.put("I409", "SAN VITTORE OLONA");
    	this.put("I410", "SANZA");
    	this.put("I411", "SANZENO");
    	this.put("I412", "SAN ZENO NAVIGLIO");
    	this.put("I414", "SAN ZENO DI MONTAGNA");
    	this.put("I415", "SAN ZENONE AL LAMBRO");
    	this.put("I416", "SAN ZENONE AL PO");
    	this.put("I417", "SAN ZENONE DEGLI EZZELINI");
    	this.put("I418", "SAONARA");
    	this.put("I420", "SAPONARA");
    	this.put("I421", "SAPPADA");
    	this.put("I422", "SAPRI");
    	this.put("I423", "SARACENA");
    	this.put("I424", "SARACINESCO");
    	this.put("I425", "SARCEDO");
    	this.put("I426", "SARCONI");
    	this.put("I428", "SARDARA");
    	this.put("I429", "SARDIGLIANO");
    	this.put("I430", "SAREGO");
    	this.put("I431", "SARENTINO .SARNTAL.");
    	this.put("I432", "SAREZZANO");
    	this.put("I433", "SAREZZO");
    	this.put("I434", "SARMATO");
    	this.put("I435", "SARMEDE");
    	this.put("I436", "SARNANO");
    	this.put("I437", "SARNICO");
    	this.put("I438", "SARNO");
    	this.put("I439", "SARNONICO");
    	this.put("I441", "SARONNO");
    	this.put("I442", "SARRE");
    	this.put("I443", "SARROCH");
    	this.put("I444", "SARSINA");
    	this.put("I445", "SARTEANO");
    	this.put("I447", "SARTIRANA LOMELLINA");
    	this.put("I448", "SARULE");
    	this.put("I449", "SARZANA");
    	this.put("I451", "SASSANO");
    	this.put("I452", "SASSARI");
    	this.put("I453", "SASSELLO");
    	this.put("I454", "SASSETTA");
    	this.put("I455", "SASSINORO");
    	this.put("I457", "SASSO DI CASTALDA");
    	this.put("I459", "SASSOCORVARO");
    	this.put("I460", "SASSOFELTRIO");
    	this.put("I461", "SASSOFERRATO");
    	this.put("I462", "SASSUOLO");
    	this.put("I463", "SATRIANO");
    	this.put("I464", "SAURIS");
    	this.put("I465", "SAUZE DI CESANA");
    	this.put("I466", "SAUZE D'OULX");
    	this.put("I467", "SAVA");
    	this.put("I468", "SAVELLI");
    	this.put("I469", "SAVIANO");
    	this.put("I470", "SAVIGLIANO");
    	this.put("I471", "SAVIGNANO IRPINO");
    	this.put("I472", "SAVIGNANO SUL RUBICONE");
    	this.put("I473", "SAVIGNANO SUL PANARO");
    	this.put("I474", "SAVIGNO");
    	this.put("I475", "SAVIGNONE");
    	this.put("I476", "SAVIORE DELL'ADAMELLO");
    	this.put("I477", "SAVOCA");
    	this.put("I478", "SAVOGNA");
    	this.put("I479", "SAVOGNA D'ISONZO");
    	this.put("I480", "SAVONA");
    	this.put("I482", "SCAFA");
    	this.put("I483", "SCAFATI");
    	this.put("I484", "SCAGNELLO");
    	this.put("I485", "SCALA COELI");
    	this.put("I486", "SCALA");
    	this.put("I487", "SCALDASOLE");
    	this.put("I489", "SCALEA");
    	this.put("I490", "SCALENGHE");
    	this.put("I492", "SCALETTA ZANCLEA");
    	this.put("I493", "SCAMPITELLA");
    	this.put("I494", "SCANDALE");
    	this.put("I496", "SCANDIANO");
    	this.put("I497", "SCANDOLARA RAVARA");
    	this.put("I498", "SCANDOLARA RIPA D'OGLIO");
    	this.put("I499", "SCANDRIGLIA");
    	this.put("I501", "SCANNO");
    	this.put("I503", "SCANO DI MONTIFERRO");
    	this.put("I504", "SCANSANO");
    	this.put("I506", "SCANZOROSCIATE");
    	this.put("I507", "SCAPOLI");
    	this.put("I510", "SCARLINO");
    	this.put("I511", "SCARMAGNO");
    	this.put("I512", "SCARNAFIGI");
    	this.put("I514", "SCARPERIA");
    	this.put("I519", "SCENA .SCHENNA.");
    	this.put("I520", "SCERNI");
    	this.put("I522", "SCHEGGIA E PASCELUPO");
    	this.put("I523", "SCHEGGINO");
    	this.put("I526", "SCHIAVI DI ABRUZZO");
    	this.put("I527", "SCHIAVON");
    	this.put("I529", "SCHIGNANO");
    	this.put("I530", "SCHILPARIO");
    	this.put("I531", "SCHIO");
    	this.put("I532", "SCHIVENOGLIA");
    	this.put("I533", "SCIACCA");
    	this.put("I534", "SCIARA");
    	this.put("I535", "SCICLI");
    	this.put("I536", "SCIDO");
    	this.put("I537", "SCILLA");
    	this.put("I538", "SCILLATO");
    	this.put("I539", "SCIOLZE");
    	this.put("I540", "SCISCIANO");
    	this.put("I541", "SCLAFANI BAGNI");
    	this.put("I543", "SCONTRONE");
    	this.put("I544", "SCOPA");
    	this.put("I545", "SCOPELLO");
    	this.put("I546", "SCOPPITO");
    	this.put("I548", "SCORDIA");
    	this.put("I549", "SCORRANO");
    	this.put("I550", "TORRIANA");
    	this.put("I551", "SCORZE'");
    	this.put("I553", "SCURCOLA MARSICANA");
    	this.put("I554", "SCURELLE");
    	this.put("I555", "SCURZOLENGO");
    	this.put("I556", "SEBORGA");
    	this.put("I558", "SECINARO");
    	this.put("I559", "SECLI'");
    	this.put("I561", "SECUGNAGO");
    	this.put("I562", "SEDEGLIANO");
    	this.put("I563", "SEDICO");
    	this.put("I564", "SEDILO");
    	this.put("I565", "SEDINI");
    	this.put("I566", "SEDRIANO");
    	this.put("I567", "SEDRINA");
    	this.put("I569", "SEFRO");
    	this.put("I570", "SEGARIU");
    	this.put("I571", "SEGGIANO");
    	this.put("I573", "SEGNI");
    	this.put("I576", "SEGONZANO");
    	this.put("I577", "SEGRATE");
    	this.put("I578", "SEGUSINO");
    	this.put("I580", "SELARGIUS");
    	this.put("I581", "SELCI");
    	this.put("I582", "SELEGAS");
    	this.put("I585", "SELLANO");
    	this.put("I588", "SELLERO");
    	this.put("I589", "SELLIA");
    	this.put("I590", "SELLIA MARINA");
    	this.put("I591", "SELVA DI VAL GARDENA .WOLKENSTEIN IN GROEDEN.");
    	this.put("I592", "SELVA DI CADORE");
    	this.put("I593", "SELVA DEI MOLINI .MUEHLWALD.");
    	this.put("I594", "SELVA DI PROGNO");
    	this.put("I595", "SELVAZZANO DENTRO");
    	this.put("I596", "SELVE MARCONE");
    	this.put("I597", "SELVINO");
    	this.put("I598", "SEMESTENE");
    	this.put("I599", "SEMIANA");
    	this.put("I600", "SEMINARA");
    	this.put("I601", "SEMPRONIANO");
    	this.put("I602", "SENAGO");
    	this.put("I603", "SENALE-SAN FELICE .UNSERE LIEBE FRAU IM WALD.");
    	this.put("I604", "SENALES .SCHNALS.");
    	this.put("I605", "SENEGHE");
    	this.put("I606", "SENERCHIA");
    	this.put("I607", "SENIGA");
    	this.put("I608", "SENIGALLIA");
    	this.put("I609", "SENIS");
    	this.put("I610", "SENISE");
    	this.put("I611", "SENNA COMASCO");
    	this.put("I612", "SENNA LODIGIANA");
    	this.put("I613", "SENNARIOLO");
    	this.put("I614", "SENNORI");
    	this.put("I615", "SENORBI'");
    	this.put("I618", "SEPINO");
    	this.put("I619", "SEPPIANA");
    	this.put("I621", "SEQUALS");
    	this.put("I622", "SERAVEZZA");
    	this.put("I624", "SERDIANA");
    	this.put("I625", "SEREGNO");
    	this.put("I626", "SEREN DEL GRAPPA");
    	this.put("I627", "SERGNANO");
    	this.put("I628", "SERIATE");
    	this.put("I629", "SERINA");
    	this.put("I630", "SERINO");
    	this.put("I631", "SERLE");
    	this.put("I632", "SERMIDE E FELONICA");
    	this.put("I633", "SIRMIONE");
    	this.put("I634", "SERMONETA");
    	this.put("I635", "SERNAGLIA DELLA BATTAGLIA");
    	this.put("I636", "SERNIO");
    	this.put("I637", "SEROLE");
    	this.put("I639", "SERRA SAN BRUNO");
    	this.put("I640", "SERRA RICCO'");
    	this.put("I641", "SERRACAPRIOLA");
    	this.put("I642", "SERRA D'AIELLO");
    	this.put("I643", "SERRA DE' CONTI");
    	this.put("I644", "SERRADIFALCO");
    	this.put("I645", "SERRALUNGA DI CREA");
    	this.put("I646", "SERRALUNGA D'ALBA");
    	this.put("I647", "SERRAMANNA");
    	this.put("I648", "SERRAMEZZANA");
    	this.put("I649", "SERRAMONACESCA");
    	this.put("I650", "SERRA PEDACE");
    	this.put("I651", "SERRAPETRONA");
    	this.put("I652", "SERRARA FONTANA");
    	this.put("I653", "SERRA SAN QUIRICO");
    	this.put("I654", "SERRA SANT'ABBONDIO");
    	this.put("I655", "SERRASTRETTA");
    	this.put("I656", "SERRATA");
    	this.put("I657", "SERRAVALLE SCRIVIA");
    	this.put("I659", "SERRAVALLE LANGHE");
    	this.put("I660", "SERRAVALLE PISTOIESE");
    	this.put("I661", "SERRAVALLE DI CHIENTI");
    	this.put("I662", "SERRAVALLE A PO");
    	this.put("I663", "SERRAVALLE SESIA");
    	this.put("I666", "SERRE");
    	this.put("I667", "SERRENTI");
    	this.put("I668", "SERRI");
    	this.put("I669", "SERRONE");
    	this.put("I670", "SERRUNGARINA");
    	this.put("I671", "SERSALE");
    	this.put("I673", "SOVRAMONTE");
    	this.put("I676", "SESSA AURUNCA");
    	this.put("I677", "SESSA CILENTO");
    	this.put("I678", "SESSAME");
    	this.put("I679", "SESSANO DEL MOLISE");
    	this.put("I681", "SESTINO");
    	this.put("I682", "SESTO CAMPANO");
    	this.put("I683", "SESTO ED UNITI");
    	this.put("I684", "SESTO FIORENTINO");
    	this.put("I686", "SESTO AL REGHENA");
    	this.put("I687", "SESTO .SEXTEN.");
    	this.put("I688", "SESTO CALENDE");
    	this.put("I689", "SESTOLA");
    	this.put("I690", "SESTO SAN GIOVANNI");
    	this.put("I692", "SESTRIERE");
    	this.put("I693", "SESTRI LEVANTE");
    	this.put("I695", "SESTU");
    	this.put("I696", "SETTALA");
    	this.put("I697", "SETTEFRATI");
    	this.put("I698", "SETTIME");
    	this.put("I699", "SETTIMO SAN PIETRO");
    	this.put("I700", "SETTIMO MILANESE");
    	this.put("I701", "SETTIMO ROTTARO");
    	this.put("I702", "SETTIMO VITTONE");
    	this.put("I703", "SETTIMO TORINESE");
    	this.put("I704", "SETTINGIANO");
    	this.put("I705", "SETZU");
    	this.put("I706", "SEUI");
    	this.put("I707", "SEULO");
    	this.put("I709", "SEVESO");
    	this.put("I711", "SEZZADIO");
    	this.put("I712", "SEZZE");
    	this.put("I714", "SFRUZ");
    	this.put("I715", "SGONICO");
    	this.put("I716", "SGURGOLA");
    	this.put("I717", "SIAMAGGIORE");
    	this.put("I718", "SIAMANNA");
    	this.put("I720", "SIANO");
    	this.put("I721", "SIAPICCIA");
    	this.put("I723", "SICULIANA");
    	this.put("I724", "SIDDI");
    	this.put("I725", "SIDERNO");
    	this.put("I726", "SIENA");
    	this.put("I727", "SIGILLO");
    	this.put("I728", "SIGNA");
    	this.put("I729", "SILANDRO .SCHLANDERS.");
    	this.put("I730", "SILANUS");
    	this.put("I732", "SILIGO");
    	this.put("I734", "SILIQUA");
    	this.put("I735", "SILIUS");
    	this.put("I736", "SILLAVENGO");
    	this.put("I737", "SILLANO");
    	this.put("I738", "SILVANO D'ORBA");
    	this.put("I739", "SILVANO PIETRA");
    	this.put("I741", "SILVI");
    	this.put("I742", "SIMALA");
    	this.put("I743", "SIMAXIS");
    	this.put("I744", "SIMBARIO");
    	this.put("I745", "SIMERI CRICHI");
    	this.put("I747", "SINAGRA");
    	this.put("I748", "SINDIA");
    	this.put("I749", "SINI");
    	this.put("I750", "SINIO");
    	this.put("I751", "SINISCOLA");
    	this.put("I752", "SINNAI");
    	this.put("I753", "SINOPOLI");
    	this.put("I754", "SIRACUSA");
    	this.put("I756", "SIRIGNANO");
    	this.put("I757", "SIRIS");
    	this.put("I758", "SIROLO");
    	this.put("I759", "SIRONE");
    	this.put("I760", "SIROR");
    	this.put("I761", "SIRTORI");
    	this.put("I763", "SISSA");
    	this.put("I765", "SIURGUS DONIGALA");
    	this.put("I767", "SIZZANO");
    	this.put("I771", "SLUDERNO .SCHLUDERNS.");
    	this.put("I772", "SMARANO");
    	this.put("I774", "SMERILLO");
    	this.put("I775", "SOAVE");
    	this.put("I777", "SOCCHIEVE");
    	this.put("I778", "SODDI'");
    	this.put("I779", "SOGLIANO AL RUBICONE");
    	this.put("I780", "SOGLIANO CAVOUR");
    	this.put("I781", "SOGLIO");
    	this.put("I782", "SOIANO DEL LAGO");
    	this.put("I783", "SOLAGNA");
    	this.put("I785", "SOLARINO");
    	this.put("I786", "SOLARO");
    	this.put("I787", "SOLAROLO");
    	this.put("I790", "SOLAROLO RAINERIO");
    	this.put("I791", "SOLARUSSA");
    	this.put("I792", "SOLBIATE");
    	this.put("I793", "SOLBIATE ARNO");
    	this.put("I794", "SOLBIATE OLONA");
    	this.put("I796", "SOLDANO");
    	this.put("I797", "SOLEMINIS");
    	this.put("I798", "SOLERO");
    	this.put("I799", "SOLESINO");
    	this.put("I800", "SOLETO");
    	this.put("I801", "SOLFERINO");
    	this.put("I802", "SOLIERA");
    	this.put("I803", "SOLIGNANO");
    	this.put("I804", "SULMONA");
    	this.put("I805", "SOLOFRA");
    	this.put("I808", "SOLONGHELLO");
    	this.put("I809", "SOLOPACA");
    	this.put("I812", "SOLTO COLLINA");
    	this.put("I813", "SOLZA");
    	this.put("I815", "SOMAGLIA");
    	this.put("I817", "SOMANO");
    	this.put("I819", "SOMMA LOMBARDO");
    	this.put("I820", "SOMMA VESUVIANA");
    	this.put("I821", "SOMMACAMPAGNA");
    	this.put("I822", "SOMMARIVA DEL BOSCO");
    	this.put("I823", "SOMMARIVA PERNO");
    	this.put("I824", "SOMMATINO");
    	this.put("I825", "SOMMO");
    	this.put("I826", "SONA");
    	this.put("I827", "SONCINO");
    	this.put("I828", "SONDALO");
    	this.put("I829", "SONDRIO");
    	this.put("I830", "SONGAVAZZO");
    	this.put("I831", "SONICO");
    	this.put("I832", "SONNINO");
    	this.put("I835", "SOPRANA");
    	this.put("I838", "SORA");
    	this.put("I839", "SORAGA DI FASSA");
    	this.put("I840", "SORAGNA");
    	this.put("I841", "SORANO");
    	this.put("I843", "SORBO SERPICO");
    	this.put("I844", "SORBO SAN BASILE");
    	this.put("I845", "SORBOLO");
    	this.put("I847", "SORDEVOLO");
    	this.put("I848", "SORDIO");
    	this.put("I849", "SORESINA");
    	this.put("I850", "SORGA'");
    	this.put("I851", "SORGONO");
    	this.put("I852", "SORI");
    	this.put("I853", "SORIANELLO");
    	this.put("I854", "SORIANO CALABRO");
    	this.put("I855", "SORIANO NEL CIMINO");
    	this.put("I856", "SORICO");
    	this.put("I857", "SORISO");
    	this.put("I858", "SORISOLE");
    	this.put("I860", "SORMANO");
    	this.put("I861", "SORRADILE");
    	this.put("I862", "SORRENTO");
    	this.put("I863", "SORSO");
    	this.put("I864", "SORTINO");
    	this.put("I865", "SOSPIRO");
    	this.put("I866", "SOSPIROLO");
    	this.put("I867", "SOSSANO");
    	this.put("I868", "SOSTEGNO");
    	this.put("I869", "SOTTO IL MONTE GIOVANNI XXIII");
    	this.put("I871", "SOVER");
    	this.put("I872", "SOVERATO");
    	this.put("I873", "SOVERE");
    	this.put("I874", "SOVERIA MANNELLI");
    	this.put("I875", "SOVERIA SIMERI");
    	this.put("I876", "SOVERZENE");
    	this.put("I877", "SOVICILLE");
    	this.put("I878", "SOVICO");
    	this.put("I879", "SOVIZZO");
    	this.put("I880", "SOZZAGO");
    	this.put("I881", "SPADAFORA");
    	this.put("I884", "SPADOLA");
    	this.put("I885", "SPARANISE");
    	this.put("I886", "SPARONE");
    	this.put("I887", "SPECCHIA");
    	this.put("I888", "SPELLO");
    	this.put("I889", "SPERA");
    	this.put("I891", "SPERLINGA");
    	this.put("I892", "SPERLONGA");
    	this.put("I893", "SPERONE");
    	this.put("I894", "SPESSA");
    	this.put("I895", "SPEZZANO ALBANESE");
    	this.put("I896", "SPEZZANO DELLA SILA");
    	this.put("I898", "SPEZZANO PICCOLO");
    	this.put("I899", "SPIAZZO");
    	this.put("I901", "SPIGNO MONFERRATO");
    	this.put("I902", "SPIGNO SATURNIA");
    	this.put("I903", "SPILAMBERTO");
    	this.put("I904", "SPILIMBERGO");
    	this.put("I905", "SPILINGA");
    	this.put("I906", "SPINADESCO");
    	this.put("I907", "SPINAZZOLA");
    	this.put("I908", "SPINEA");
    	this.put("I909", "SPINEDA");
    	this.put("I910", "SPINETE");
    	this.put("I911", "SPINETO SCRIVIA");
    	this.put("I912", "SPINETOLI");
    	this.put("I914", "SPINO D'ADDA");
    	this.put("I916", "SPINONE AL LAGO");
    	this.put("I917", "SPINOSO");
    	this.put("I919", "SPIRANO");
    	this.put("I921", "SPOLETO");
    	this.put("I922", "SPOLTORE");
    	this.put("I923", "SPONGANO");
    	this.put("I924", "SPORMAGGIORE");
    	this.put("I925", "SPORMINORE");
    	this.put("I926", "SPOTORNO");
    	this.put("I927", "SPRESIANO");
    	this.put("I928", "SPRIANA");
    	this.put("I929", "SQUILLACE");
    	this.put("I930", "SQUINZANO");
    	this.put("I932", "STAFFOLO");
    	this.put("I935", "STAGNO LOMBARDO");
    	this.put("I936", "STAITI");
    	this.put("I937", "STALETTI'");
    	this.put("I938", "STANGHELLA");
    	this.put("I939", "STARANZANO");
    	this.put("I941", "STAZZANO");
    	this.put("I942", "STAZZEMA");
    	this.put("I943", "STAZZONA");
    	this.put("I945", "STEFANACONI");
    	this.put("I946", "STELLA");
    	this.put("I947", "STELLANELLO");
    	this.put("I948", "STELVIO .STILFS.");
    	this.put("I949", "STENICO");
    	this.put("I950", "STERNATIA");
    	this.put("I951", "STEZZANO");
    	this.put("I952", "STIA");
    	this.put("I953", "STIENTA");
    	this.put("I954", "STIGLIANO");
    	this.put("I955", "STIGNANO");
    	this.put("I956", "STILO");
    	this.put("I959", "STIMIGLIANO");
    	this.put("I960", "STIO");
    	this.put("I962", "STORNARA");
    	this.put("I963", "STORNARELLA");
    	this.put("I964", "STORO");
    	this.put("I965", "STRA");
    	this.put("I968", "STRADELLA");
    	this.put("I969", "STRAMBINELLO");
    	this.put("I970", "STRAMBINO");
    	this.put("I973", "STRANGOLAGALLI");
    	this.put("I974", "STREGNA");
    	this.put("I975", "STREMBO");
    	this.put("I976", "STRESA");
    	this.put("I977", "STREVI");
    	this.put("I978", "STRIANO");
    	this.put("I979", "STRIGNO");
    	this.put("I980", "STRONA");
    	this.put("I981", "STRONCONE");
    	this.put("I982", "STRONGOLI");
    	this.put("I984", "STROPPIANA");
    	this.put("I985", "STROPPO");
    	this.put("I986", "STROZZA");
    	this.put("I990", "STURNO");
    	this.put("I991", "SUBBIANO");
    	this.put("I992", "SUBIACO");
    	this.put("I993", "SUCCIVO");
    	this.put("I994", "SUEGLIO");
    	this.put("I995", "SUELLI");
    	this.put("I996", "SUELLO");
    	this.put("I997", "SUISIO");
    	this.put("I998", "SULBIATE");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
